export const productsData = {
    0: {
        id: 0,
        title: 'Lancetas',
        price: 8.99,
        description: 'Permite realizar una punción en la piel para obtener sangre, también usado en las estéticas para sacar espinillas y puntos negros. Caja con 100 unidades.',
        rating: 4,
        reviews: 89,
        images: [],
        categories: 'Insumos Médicos, Desechables',
        tags: 'Lancetas, Estética, Punción'
    },
    1: {
        id: 1,
        title: 'Gel Ultrasonido',
        price: 15.50,
        description: 'Gel que contribuye a la lubricación durante el ultrasonido u otros procedimientos. También es usado en la depilación laser, radiofrecuencia o ultrasonidos. No daña el transductor, se extiende fácil y uniformemente, no irrita la piel. Cantidad 5 litros.',
        rating: 4,
        reviews: 124,
        images: [],
        categories: 'Insumos Médicos, Estética',
        tags: 'Ultrasonido, Gel, Lubricante'
    },
    2: {
        id: 2,
        title: 'Micropore 3M',
        price: 6.75,
        description: 'Cinta suave y amable con la piel, de papel que se usa para curar las heridas y asegurar los tubos médicos y apósitos. Tamaño: 2,5 x 9,1 mts.',
        rating: 5,
        reviews: 203,
        images: [],
        categories: 'Curación, Insumos Médicos',
        tags: 'Micropore, 3M, Cinta Médica'
    },
    3: {
        id: 3,
        title: 'Bolsas para Esterilizar',
        price: 12.99,
        description: 'Papel grado médico, indicado para el proceso de esterilización, diferentes tamaños disponibles. Caja con 200 unidades.',
        rating: 4,
        reviews: 67,
        images: [],
        categories: 'Esterilización, Insumos Médicos',
        tags: 'Esterilización, Bolsas, Médico'
    },
    4: {
        id: 4,
        title: 'Rollo para Esterilizar',
        price: 18.50,
        description: 'Rollo de bolsas para esterilización de diferentes instrumentos, papel grados médico, cada rollo contiene 200 metros, hay de diferentes tamaños.',
        rating: 4,
        reviews: 45,
        images: [],
        categories: 'Esterilización, Insumos Médicos',
        tags: 'Esterilización, Rollo, Papel Médico'
    },
    5: {
        id: 5,
        title: 'Barrera Adhesiva',
        price: 9.99,
        description: 'Film adhesivo que se emplea para no dejar residuos de ningún tipo sea la superficie que sea. Desechable, fácil de aplicar y quitar, no deja ningún residuo.',
        rating: 4,
        reviews: 78,
        images: [],
        categories: 'Protección, Insumos Médicos',
        tags: 'Barrera, Adhesiva, Protección'
    },
    6: {
        id: 6,
        title: 'Pads de Yodo',
        price: 7.25,
        description: 'Ideal para preparación de la piel antiséptica y otros procedimientos invasivos menores. Almohadilla impregnada con povidona yodada al 10%. Caja con 100 unidades.',
        rating: 5,
        reviews: 156,
        images: [],
        categories: 'Antisépticos, Curación',
        tags: 'Yodo, Antiséptico, Pads'
    },
    7: {
        id: 7,
        title: 'Pads de Alcohol',
        price: 5.99,
        description: 'Toallitas impregnadas en alcohol de 70%, para desinfectar heridas, cortes o áreas pequeñas antes de realizar un procedimiento. Caja con 100 unidades.',
        rating: 4,
        reviews: 189,
        images: [],
        categories: 'Desinfección, Curación',
        tags: 'Alcohol, Desinfectante, Pads'
    },
    8: {
        id: 8,
        title: 'Suctor de Saliva',
        price: 4.50,
        description: 'Conocido como eyector de saliva o suctor. Su función es succionar el exceso de saliva, agua o sangre, se dobla fácilmente, no tiene memoria al momento de doblarse, longitud de 15cm. Paquete con 100 unidades.',
        rating: 4,
        reviews: 92,
        images: [],
        categories: 'Odontología, Insumos Médicos',
        tags: 'Suctor, Saliva, Odontología'
    },
    9: {
        id: 9,
        title: 'Cubre Zapatos',
        price: 6.25,
        description: 'Protegen el calzado, evitando la transmisión de gérmenes y disminuyen la cantidad de suciedad. Hecho de tela no tejida y con antideslizante. Paquete con 100 unidades.',
        rating: 4,
        reviews: 134,
        images: [],
        categories: 'Protección Personal, EPP',
        tags: 'Cubre Zapatos, Protección, Hospital'
    },
    10: {
        id: 10,
        title: 'Bata sin Manga',
        price: 14.99,
        description: 'Bata de un solo uso fabricada con tela no tejida SMS, sin mangas y con cierre trasero de cintas para atar al cuello y a la cintura. Paquete con 10 unidades. Talla: Única.',
        rating: 4,
        reviews: 167,
        images: [],
        categories: 'Ropa Médica, Protección',
        tags: 'Bata, Desechable, Médico'
    },
    11: {
        id: 11,
        title: 'Bata Manga Larga',
        price: 18.75,
        description: 'Bata de un solo uso fabricada con tela no tejida SMS, mangas larga, con puño de elástico o de algodón y con cierre trasero de cintas para atar al cuello y a la cintura. Paquete con 10 unidades. Talla: Única.',
        rating: 5,
        reviews: 198,
        images: [],
        categories: 'Ropa Médica, Protección',
        tags: 'Bata, Manga Larga, Protección'
    },
    12: {
        id: 12,
        title: 'Sábana sin Elástico',
        price: 11.50,
        description: 'Superficie suave, resistente a líquidos, no estéril y de un solo uso, hecha de polipropileno (no tejida), diseñada para su uso en mesas de masaje, camillas y cobertor en salones de belleza. Paquete con 10 unidades.',
        rating: 4,
        reviews: 112,
        images: [],
        categories: 'Estética, Insumos',
        tags: 'Sábana, Estética, Masaje'
    },
    13: {
        id: 13,
        title: 'Cubre Camilla',
        price: 13.25,
        description: 'Superficie suave, tiene elástico en los bordes, resistente a líquidos, no estéril y de un solo uso, hecha de polipropileno (no tejida), diseñada para su uso en mesas de masaje, camillas y cobertor en salones de belleza. Paquete con 10 unidades.',
        rating: 4,
        reviews: 145,
        images: [],
        categories: 'Estética, Insumos Médicos',
        tags: 'Cubre Camilla, Estética, Protección'
    },
    14: {
        id: 14,
        title: 'Cubre Barba',
        price: 5.99,
        description: 'Se usa para cubrir el vello facial y evitar que el pelo suelto caiga en un espacio de trabajo, retiene la caída del vello facial durante la manipulación de alimentos u otros artículos. Se usa en laboratorios, industria alimentaria, labores de limpieza. Paquete con 100 unidades.',
        rating: 4,
        reviews: 87,
        images: [],
        categories: 'Protección Personal, EPP',
        tags: 'Cubre Barba, Protección, Alimentos'
    },
    15: {
        id: 15,
        title: 'Babero Servitoallas',
        price: 8.75,
        description: 'Utilizada para hacer manicure como paño para cualquier derrame, para pedicure como separador de dedos de los pies, también para tinte y cortar el pelo en la parte trasera de la cabeza, cobertor de cabecera, protegiendo de todo tipo de contaminantes, y los odontólogos como baberos. Paquete de 125 unidades.',
        rating: 4,
        reviews: 176,
        images: [],
        categories: 'Estética, Odontología',
        tags: 'Babero, Servitoallas, Estética'
    },
    16: {
        id: 16,
        title: 'Capucha Protectora',
        price: 7.50,
        description: 'Aisla el pelo y cubre totalmente la cabeza en tareas con mayor riesgo de contaminación o infección. Mantiene la higiene y la seguridad. Paquete con 100 unidades.',
        rating: 4,
        reviews: 98,
        images: [],
        categories: 'Protección Personal, EPP',
        tags: 'Capucha, Protección, Higiene'
    },
    17: {
        id: 17,
        title: 'Gorro Clip o Acordeón',
        price: 6.99,
        description: 'Para evitar la caída de cabello, viene en forma de gusanito o acordeón, varios colores disponibles. Paquete de 100 unidades.',
        rating: 4,
        reviews: 123,
        images: [],
        categories: 'Protección Personal, Estética',
        tags: 'Gorro, Acordeón, Protección'
    },
    18: {
        id: 18,
        title: 'Gorro Malla',
        price: 5.25,
        description: 'Para evitar la caída del cabello, ideal para hoteles, restaurantes, cafeterías, y tareas de limpieza. Paquete con 100 unidades.',
        rating: 4,
        reviews: 156,
        images: [],
        categories: 'Protección Personal, Alimentos',
        tags: 'Gorro Malla, Protección, Alimentos'
    },
    19: {
        id: 19,
        title: 'Aceite para Masaje',
        price: 12.99,
        description: 'Aceite a base de uva y extractos naturales, no contiene aceite mineral, es decir proveniente del petróleo. Tamaños: 250ml, litro o galón.',
        rating: 5,
        reviews: 234,
        images: [],
        categories: 'Estética, Masajes',
        tags: 'Aceite, Masaje, Natural'
    },
    20: {
        id: 20,
        title: 'Aplicadores Largos',
        price: 4.99,
        description: 'Sirve para aplicar cualquier tipo de sustancia, limpia, desinfecta y absorbe, no estéril, de 6 pulgadas. Paquete con 100 unidades.',
        rating: 4,
        reviews: 87,
        images: [],
        categories: 'Insumos Médicos, Desechables',
        tags: 'Aplicadores, Largos, Desechables'
    },
    21: {
        id: 21,
        title: 'Aplicador Corto',
        price: 3.99,
        description: 'Sirve para aplicar cualquier tipo de sustancia, limpia, desinfecta y absorbe, no estéril, de 3 pulgadas. Paquete con 100 unidades.',
        rating: 4,
        reviews: 76,
        images: [],
        categories: 'Insumos Médicos, Desechables',
        tags: 'Aplicadores, Cortos, Desechables'
    },
    22: {
        id: 22,
        title: 'Venda Coban',
        price: 8.50,
        description: 'Venda elástica autoadherente, se fija sobre si misma, se usa para lesiones, esguinces y para proteger apósitos y dispositivos. Tamaño 5cm x 4.5m.',
        rating: 5,
        reviews: 145,
        images: [],
        categories: 'Curación, Ortopedia',
        tags: 'Venda, Coban, Elástica'
    },
    23: {
        id: 23,
        title: 'Gasa No Tejida',
        price: 9.25,
        description: '100% algodonada, extra absorbente, bajo en pelusa, libre de látex, no tejida, de un solo uso, no estéril, paquete de 200 unidades. Diferentes tamaños disponibles: 2x2, 3x3, 4x4.',
        rating: 4,
        reviews: 167,
        images: [],
        categories: 'Curación, Insumos Médicos',
        tags: 'Gasa, No Tejida, Absorbente'
    },
    24: {
        id: 24,
        title: 'Esterilix Equipos',
        price: 22.99,
        description: 'Desinfectante de alto nivel de uso directo, formulada para la eliminación de todo tipo de microorganismos, patógenos.',
        rating: 5,
        reviews: 89,
        images: [],
        categories: 'Limpieza, Desinfección',
        tags: 'Esterilix, Desinfectante, Equipos'
    },
    25: {
        id: 25,
        title: 'Esterilix Superficie',
        price: 18.75,
        description: 'Desinfectante ya diluido de aplicación directa con aspersión, para facilitar el uso ya que no requiere enjuague y es de fácil aplicación, especialmente formulada para la eliminación y prevención de contaminación biológica de microorganismos patógenos.',
        rating: 4,
        reviews: 112,
        images: [],
        categories: 'Limpieza, Desinfección',
        tags: 'Esterilix, Superficie, Desinfectante'
    },
    26: {
        id: 26,
        title: 'Esterilix X-7',
        price: 25.50,
        description: 'Indicado para la desinfección en frío de instrumental, equipo medico o superficie.',
        rating: 4,
        reviews: 78,
        images: [],
        categories: 'Limpieza, Desinfección',
        tags: 'Esterilix, X-7, Desinfección'
    },
    27: {
        id: 27,
        title: 'Cleaner 256',
        price: 32.99,
        description: 'Limpiador desinfectante concentrado de uso profesional y de amplio espectro que combina tres principios activos: aldehídos, alcoholes y amonios cuaternarios de quinta generación. Rinde hasta 256 veces su presentación.',
        rating: 5,
        reviews: 134,
        images: [],
        categories: 'Limpieza, Desinfección',
        tags: 'Cleaner, 256, Concentrado'
    },
    28: {
        id: 28,
        title: 'Detercel Enzimático',
        price: 19.99,
        description: 'Detergente multienzimático líquido, diseñado para la limpieza de instrumental, equipo médico u odontológico. Contiene proteasas, amilasas y lipasas, es un detergente no iónico que ha sido formulado con antioxidantes para evitar oxidación de instrumental y equipos en los que se emplee.',
        rating: 4,
        reviews: 96,
        images: [],
        categories: 'Limpieza, Enzimático',
        tags: 'Detercel, Enzimático, Detergente'
    },
    29: {
        id: 29,
        title: 'Neutralizador de Olor',
        price: 14.50,
        description: 'Neutralizan olores no deseados, como el tabaco, materia en descomposición y la humedad. Los elimina por completo, dejando aire fresco, limpio y natural.',
        rating: 4,
        reviews: 145,
        images: [],
        categories: 'Limpieza, Ambientadores',
        tags: 'Neutralizador, Olor, Ambientador'
    },
    30: {
        id: 30,
        title: 'Cloridex',
        price: 16.75,
        description: 'Puede ser usado como limpiador de manos. Como antiséptico quirúrgico para preparar la piel del paciente preoperatorio. Como limpiador de heridas cutáneas y limpiador de piel en general (acné, foliculitis de la barba y otras infecciones de la piel).',
        rating: 5,
        reviews: 223,
        images: [],
        categories: 'Antisépticos, Higiene',
        tags: 'Cloridex, Antiséptico, Quirúrgico'
    },
    31: {
        id: 31,
        title: 'Agua Destilada',
        price: 3.99,
        description: 'Es resultado de un proceso de purificación por el cual se eliminan una gran cantidad de impurezas características en el agua doméstica y se eliminan iones.',
        rating: 4,
        reviews: 178,
        images: [],
        categories: 'Insumos Médicos, Laboratorio',
        tags: 'Agua, Destilada, Purificada'
    },
    32: {
        id: 32,
        title: 'Agua Oxigenada',
        price: 4.25,
        description: 'Se utiliza para productos de limpieza y de cuidado personal como: Colorantes, blanqueadores, quita manchas, limpiador de baño, entre otros.',
        rating: 4,
        reviews: 156,
        images: [],
        categories: 'Limpieza, Cuidado Personal',
        tags: 'Agua, Oxigenada, Blanqueador'
    },
    33: {
        id: 33,
        title: 'Alcohol Líquido',
        price: 7.50,
        description: 'Incoloro, volátil, con olor característico. Es muy usado como disolventes, se usa en mezclas anticongelantes, como combustible, como antiséptico, y muchas funciones más.',
        rating: 4,
        reviews: 189,
        images: [],
        categories: 'Antisépticos, Limpieza',
        tags: 'Alcohol, Líquido, Antiséptico'
    },
    34: {
        id: 34,
        title: 'Lavaplatos Multiacción',
        price: 5.99,
        description: 'La Crema Lavaplatos Multiacción es un producto diseñado para remover suciedad de vajillas y otros implementos utilizados comúnmente en el área de cocina, mediante el lavado manual. Contiene microabrasivos que facilitan la remoción de grasas a la vez que en su formulación se incluyen agentes humectantes para evitar resecar la piel.',
        rating: 4,
        reviews: 234,
        images: [],
        categories: 'Limpieza, Cocina',
        tags: 'Lavaplatos, Multiacción, Limpieza'
    },
    35: {
        id: 35,
        title: 'Alcohol en Gel 300ml',
        price: 6.25,
        description: 'Reconocido por su rápida actividad contra una amplia gama de virus, bacterias y virus, hongos, no requiere enjuague, fácil aplicación.',
        rating: 5,
        reviews: 267,
        images: [],
        categories: 'Higiene, Antisépticos',
        tags: 'Alcohol, Gel, Desinfectante'
    },
    36: {
        id: 36,
        title: 'Alcohol en Gel',
        price: 8.99,
        description: 'Reconocido por su rápida actividad contra una amplia gama de virus, bacterias y virus, hongos, no requiere enjuague, fácil aplicación.',
        rating: 5,
        reviews: 189,
        images: [],
        categories: 'Higiene, Antisépticos',
        tags: 'Alcohol, Gel, Desinfectante'
    },
    37: {
        id: 37,
        title: 'Jabón Líquido',
        price: 4.75,
        description: 'El Jabón Líquido para Manos está diseñado para la limpieza y humectación de las manos, sin provocar resequedad después de su aplicación. Disponible en diferentes cromas y neutro.',
        rating: 4,
        reviews: 278,
        images: [],
        categories: 'Higiene, Cuidado Personal',
        tags: 'Jabón, Líquido, Manos'
    },
    38: {
        id: 38,
        title: 'Cinta Testigo',
        price: 9.50,
        description: 'Es utilizado principalmente en procesos de esterilización y control de calidad. Su función básica es servir como indicador químico que verifica si ha sido expuesto a un proceso de esterilización (por ejemplo, vapor, óxido de etileno o plasma). Cambia de color al ser sometida a las condiciones adecuadas.',
        rating: 4,
        reviews: 67,
        images: [],
        categories: 'Esterilización, Control Calidad',
        tags: 'Cinta, Testigo, Esterilización'
    },
    39: {
        id: 39,
        title: 'Mascarilla KN95',
        price: 12.99,
        description: 'Tira de nariz ajustable, evita la entrada de aire contaminado, 5 capas, varios colores disponibles. Caja de 10 o 20 unidades.',
        rating: 5,
        reviews: 345,
        images: [],
        categories: 'Protección Personal, Mascarillas',
        tags: 'KN95, Mascarilla, Protección'
    },
    40: {
        id: 40,
        title: 'Mascarilla N95',
        price: 14.50,
        description: 'Mascarilla cónica, con tira de nariz ajustable para evitar la entrada de aire contaminado, polvo, bacterias y virus.',
        rating: 5,
        reviews: 298,
        images: [],
        categories: 'Protección Personal, Mascarillas',
        tags: 'N95, Mascarilla, Protección'
    },
    41: {
        id: 41,
        title: 'Mascarilla KF94',
        price: 13.75,
        description: 'Esta mascarilla protectora cuenta con cuatro capas y con un clip nasal metálico para poder ajustarlo mejor, desechables. Paquete con 10 o 20 unidades.',
        rating: 4,
        reviews: 234,
        images: [],
        categories: 'Protección Personal, Mascarillas',
        tags: 'KF94, Mascarilla, Coreana'
    },
    42: {
        id: 42,
        title: 'Cubre Boca',
        price: 6.99,
        description: 'Tira de nariz ajustable, evita la entrada de aire contaminado, 3 capas, desechables, varios colores y estampados disponibles. Caja con 50 unidades.',
        rating: 4,
        reviews: 189,
        images: [],
        categories: 'Protección Personal, Mascarillas',
        tags: 'Cubre Boca, Desechable, Protección'
    },
    43: {
        id: 43,
        title: 'Vaselina en Pasta',
        price: 5.25,
        description: 'En pasta para uso tópico, no irrita la piel, no produce mal olor, calma reacciones de la piel como picazón.',
        rating: 4,
        reviews: 156,
        images: [],
        categories: 'Cuidado Personal, Dermatología',
        tags: 'Vaselina, Pasta, Piel'
    },
    44: {
        id: 44,
        title: 'Rollo Plástico',
        price: 11.99,
        description: 'Rollo plástico fino, transparente, resistente y estirable, con diferentes usos, envuelve y protege las camillas de la suciedad y polvo. Tamaños: 18 pulgadas y 6 pulgadas.',
        rating: 4,
        reviews: 98,
        images: [],
        categories: 'Protección, Insumos',
        tags: 'Rollo, Plástico, Protección'
    },
    45: {
        id: 45,
        title: 'Vasos de Cartón',
        price: 3.50,
        description: 'Vasos desechables de cartón, amigable con el ambiente, utilizados en clínicas dentales y para el enjuague bucal de los pacientes capacidad de 3oz. Paquete: 50 unidades y 100 unidades.',
        rating: 4,
        reviews: 145,
        images: [],
        categories: 'Desechables, Odontología',
        tags: 'Vasos, Cartón, Desechables'
    },
    46: {
        id: 46,
        title: 'Vasos Plásticos',
        price: 4.25,
        description: 'Vasos desechables utilizados en clínicas dentales y para el enjuague bucal de los pacientes, es de plásticos, capacidad de 3 oz. Paquete con 50 unidades y 100 unidades.',
        rating: 4,
        reviews: 167,
        images: [],
        categories: 'Desechables, Odontología',
        tags: 'Vasos, Plásticos, Desechables'
    },
    47: {
        id: 47,
        title: 'Rollo de Algodón',
        price: 7.99,
        description: 'Algodón enrollado, se puede cortar según requiera el usuario, no estéril, es blanco, absorbente y purificado. Tamaño: 500 gramos.',
        rating: 4,
        reviews: 134,
        images: [],
        categories: 'Curación, Insumos Médicos',
        tags: 'Algodón, Rollo, Absorbente'
    },
    48: {
        id: 48,
        title: 'Algodón Torunda',
        price: 5.75,
        description: 'La torunda es una bola de algodón, lista para usar, alta absorción. También es conocido como algodón en bolitas.',
        rating: 4,
        reviews: 189,
        images: [],
        categories: 'Curación, Insumos Médicos',
        tags: 'Algodón, Torunda, Bolitas'
    },
    49: {
        id: 49,
        title: 'Rodillo Dental',
        price: 8.50,
        description: 'Herramienta utilizada en odontología para diversas aplicaciones. Sirven para separar y aislar los tejidos, suave, flexible. Paquete con 500 y 1000 unidades.',
        rating: 4,
        reviews: 78,
        images: [],
        categories: 'Odontología, Instrumental',
        tags: 'Rodillo, Dental, Odontología'
    },
    50: {
        id: 50,
        title: 'Guantes de Plástico',
        price: 4.99,
        description: 'Son transparentes, ambidiestros, aptos para el contacto con alimentos. El uso de estos guantes permite evita la contaminación de productos que van a ser manipulados con las manos. Paquete con 100 unidades.',
        rating: 4,
        reviews: 156,
        images: [],
        categories: 'Protección, Guantes',
        tags: 'Guantes, Plástico, Alimentos'
    },
    51: {
        id: 51,
        title: 'Latex Bajos en Polvo',
        price: 9.25,
        description: 'Gran adaptabilidad a la mano, mayor sensibilidad al tacto, ambidiestro, hecho de caucho natural, biodegradable gran protección ante químicos y fluidos corporales, puede causar reacciones alérgicas. Caja con 100 unidades.',
        rating: 4,
        reviews: 234,
        images: [],
        categories: 'Protección, Guantes',
        tags: 'Latex, Bajos Polvo, Guantes'
    },
    52: {
        id: 52,
        title: 'Latex Sin Polvo',
        price: 10.50,
        description: 'Gran adaptabilidad a la mano, mayor sensibilidad al tacto, ambidiestro, hecho de caucho natural, biodegradable gran protección ante químicos y fluidos corporales, puede causar reacciones alérgicas. Caja con 100 unidades.',
        rating: 5,
        reviews: 189,
        images: [],
        categories: 'Protección, Guantes',
        tags: 'Latex, Sin Polvo, Guantes'
    },
    53: {
        id: 53,
        title: 'Vinyl',
        price: 7.75,
        description: 'Ambidiestro, libre de polvo, mayor permeabilidad, libre de látex y es usualmente usado en el manejo de alimentos y para tareas de corta duración, menor adaptación. Caja con 100 unidades.',
        rating: 4,
        reviews: 167,
        images: [],
        categories: 'Protección, Guantes',
        tags: 'Vinyl, Guantes, Alimentos'
    },
    54: {
        id: 54,
        title: 'Guantes de Alto Riesgo',
        price: 15.99,
        description: 'Diseñado para protección personal y proporcionar seguridad adicional en entornos de trabajo con riesgos elevados para la salud de los trabajadores. Son utilizados en procedimientos con riesgo de contacto con agentes químicos, físicos y biológicos, y protegen contra cortes, punciones y contacto con sustancias peligrosas, son más largos y gruesos.',
        rating: 5,
        reviews: 89,
        images: [],
        categories: 'Protección, Guantes',
        tags: 'Alto Riesgo, Protección, Químicos'
    },
    55: {
        id: 55,
        title: 'Guantes Texturizados',
        price: 11.25,
        description: 'Agarre antideslizante, mayor resistencia y grosor, multiusos, sin polvo, no estéril, ambidiestro, gramaje: 8,5.',
        rating: 4,
        reviews: 134,
        images: [],
        categories: 'Protección, Guantes',
        tags: 'Texturizados, Antideslizante, Guantes'
    },
    56: {
        id: 56,
        title: 'Vinyl de Color',
        price: 8.99,
        description: 'Ambidiestro, libre de polvo, mayor permeabilidad, libre de látex y es usualmente usado en el manejo de alimentos y para tareas de corta duración, menor adaptación, elaborado con 30% vinyl y 70% nitrilo, es mas resistente que el vinyl, pero menos resistente que el nitrilo. Caja con 100 unidades.',
        rating: 4,
        reviews: 156,
        images: [],
        categories: 'Protección, Guantes',
        tags: 'Vinyl, Color, Guantes'
    },
    57: {
        id: 57,
        title: 'Guantes de Nitrilo',
        price: 12.50,
        description: 'Hecho de caucho sintético, se adapta bien a la mano, no produce alergia, texturizado en la punta de los dedos, ambidiestro, libre de polvo, y libre de látex, gran variedad de colores. Caja con 100 unidades.',
        rating: 5,
        reviews: 278,
        images: [],
        categories: 'Protección, Guantes',
        tags: 'Nitrilo, Guantes, Sin Látex'
    },
    58: {
        id: 58,
        title: 'Guantes Afelpados',
        price: 6.75,
        description: 'Guantes multipropósito cuidan tus manos y uñas; son tan delgados que permitirán que no pierdas sensibilidad al lavar. Su superficie texturizada sobre la palma de la mano ayuda a evitar que se te resbalen los platos vasos y utensilios.',
        rating: 4,
        reviews: 189,
        images: [],
        categories: 'Limpieza, Protección',
        tags: 'Afelpados, Lavado, Protección'
    },
    59: {
        id: 59,
        title: 'Guantes Quirúrgicos',
        price: 16.99,
        description: 'Guantes de látex estériles, mayor elasticidad, resistencia al desgarro, superficie micro texturizada un excelente agarre del instrumento y acabado antideslizante. Caja con 50 pares.',
        rating: 5,
        reviews: 145,
        images: [],
        categories: 'Quirúrgico, Guantes',
        tags: 'Quirúrgicos, Estériles, Látex'
    },
    60: {
        id: 60,
        title: 'Papel para Camilla',
        price: 9.75,
        description: 'Para proteger las camillas y para ofrecer una mayor higiene durante la atención de los clientes. Tamaño: 54cm x 38mts.',
        rating: 4,
        reviews: 112,
        images: [],
        categories: 'Estética, Insumos',
        tags: 'Papel, Camilla, Protección'
    },
    61: {
        id: 61,
        title: 'Paletas de Madera',
        price: 3.99,
        description: 'Se puedes mezclar, batir y aplicar productos como cremas, ceras y gel conductor, no estéril. Producto descartable hecho de madera 100% natural de superficie suave. Paquete con 100 unidades.',
        rating: 4,
        reviews: 134,
        images: [],
        categories: 'Estética, Desechables',
        tags: 'Paletas, Madera, Aplicadores'
    },
    62: {
        id: 62,
        title: 'Oxímetro',
        price: 24.99,
        description: 'Ayuda a medir la cantidad de oxígeno que posee nuestra sangre, se adapta a los diferentes tamaños de dedos.',
        rating: 5,
        reviews: 267,
        images: [],
        categories: 'Monitoreo, Médico',
        tags: 'Oxímetro, Saturación, Salud'
    },
    63: {
        id: 63,
        title: 'K9 Pro',
        price: 89.99,
        description: 'Control automatizado de medición de temperatura corporal con aerosol integrado que hace que la desinfección de las manos sea más conveniente y segura para todos los usuarios.',
        rating: 4,
        reviews: 78,
        images: [],
        categories: 'Tecnología, Seguridad',
        tags: 'K9 Pro, Temperatura, Desinfección'
    },
    64: {
        id: 64,
        title: 'Rollo de Papel Toalla',
        price: 8.25,
        description: 'Rollo de toallas absorbentes y resistentes. Se recomienda para lugares que requieren de alta capacidad y valor. Es un producto de limpieza indispensable para proveer higiene en el secado de manos así como superficies.',
        rating: 4,
        reviews: 189,
        images: [],
        categories: 'Limpieza, Higiene',
        tags: 'Papel, Toalla, Rollo'
    },
    65: {
        id: 65,
        title: 'Toallas de Papel para Manos',
        price: 7.50,
        description: 'Toallas interfolíadas, dispensadas una a una, evitando la contaminación cruzada, forma rectangular. Tamaño: 22,5cm x 23cm. Paquete con 200 unidades.',
        rating: 4,
        reviews: 156,
        images: [],
        categories: 'Limpieza, Higiene',
        tags: 'Toallas, Papel, Manos'
    },
    66: {
        id: 66,
        title: 'Bata Impermeable',
        price: 22.99,
        description: 'Impermeable, plástica con sujeción, para usarse en procedimientos médicos con probabilidad de contacto con fluidos corporales o portadores de patógenos, espalda abierta. No estéril. Paquete con 10 unidades.',
        rating: 5,
        reviews: 134,
        images: [],
        categories: 'Protección, Ropa Médica',
        tags: 'Bata, Impermeable, Protección'
    },
    67: {
        id: 67,
        title: 'Camilla Hidráulica',
        price: 450.00,
        description: 'Brazos abatibles y ajustable soporte de piernas ajustables, cabecera removible, pistón de aire para ajustar la altura.',
        rating: 5,
        reviews: 45,
        images: [],
        categories: 'Equipamiento, Médico',
        tags: 'Camilla, Hidráulica, Ajustable'
    },
    68: {
        id: 68,
        title: 'Banco Giratorio con Respaldo',
        price: 120.00,
        description: 'Hecho de aluminio, hierro esmaltado y vinyl, altura ajustable, con respaldar, varios colores a elegir.',
        rating: 4,
        reviews: 67,
        images: [],
        categories: 'Muebles, Estética',
        tags: 'Banco, Giratorio, Respaldo'
    },
    69: {
        id: 69,
        title: 'Canilla Fija',
        price: 280.00,
        description: 'Camillas cómoda, resistente, fija, soporta un peso aproximado de 150 kilos, apta para realizar masajes, tatuajes, microblading, lashista, etc. 6 diferentes estilos y varios colores a elegir.',
        rating: 4,
        reviews: 89,
        images: [],
        categories: 'Muebles, Estética',
        tags: 'Canilla, Fija, Masajes'
    },
    70: {
        id: 70,
        title: 'Banco Giratorio sin Respaldo',
        price: 95.00,
        description: 'Hecho de aluminio, hierro esmaltado y vinyl, altura ajustable, sin respaldar, varios colores a elegir.',
        rating: 4,
        reviews: 56,
        images: [],
        categories: 'Muebles, Estética',
        tags: 'Banco, Giratorio, Sin Respaldo'
    },
    71: {
        id: 71,
        title: 'Camilla Tipo Maleta',
        price: 320.00,
        description: 'Camillas cómoda, resistente, fácil de movilizar, soporta un peso aproximado de 150 kilos, apta para realizar masajes, tatuajes, microblading, lashista, etc. 6 diferentes estilos y varios colores a elegir.',
        rating: 5,
        reviews: 78,
        images: [],
        categories: 'Muebles, Portátil',
        tags: 'Camilla, Maleta, Portátil'
    },
    72: {
        id: 72,
        title: 'Apoya Brazos',
        price: 45.00,
        description: 'Hecho de aluminio, hierro esmaltado y vinyl, altura ajustable, varios colores a elegir.',
        rating: 4,
        reviews: 34,
        images: [],
        categories: 'Accesorios, Estética',
        tags: 'Apoya, Brazos, Ajustable'
    },
    73: {
        id: 73,
        title: 'Gorro de Cirugía',
        price: 6.25,
        description: 'Diseñado para proteger la cabeza y el cabello de los trabajadores de la salud de posibles contaminantes. Ofrece resistencia para proteger el cabello y el cuero cabelludo durante las cirugías. Paquete con 100 unidades.',
        rating: 4,
        reviews: 112,
        images: [],
        categories: 'Protección Personal, EPP',
        tags: 'Gorro, Cirugía, Protección'
    },
    74: {
        id: 74,
        title: 'Careta Protectora',
        price: 8.99,
        description: 'Barrera simple para ayudar a evitar que las gotas respiratorias viajen en el aire y sobre otras personas, ligero y cómodo.',
        rating: 4,
        reviews: 189,
        images: [],
        categories: 'Protección Personal, EPP',
        tags: 'Careta, Protectora, Facial'
    },
    75: {
        id: 75,
        title: 'Careta con Lentes',
        price: 12.50,
        description: 'Barrera simple para ayudar a evitar que las gotas respiratorias viajen en el aire y sobre otras personas, ligero y cómodo, hecha de material PET. Espacio para anteojos o gafas. Caja con 6 unidades.',
        rating: 5,
        reviews: 145,
        images: [],
        categories: 'Protección Personal, EPP',
        tags: 'Careta, Lentes, Protección'
    },
    76: {
        id: 76,
        title: 'Kimono Protector',
        price: 18.75,
        description: 'Traje de protección, hecho de un material resistente el cual ayuda a proporcionar una barrera de protección contra salpicaduras de líquidos, polvos tóxicos y ciertos contaminantes biológicos.',
        rating: 4,
        reviews: 89,
        images: [],
        categories: 'Protección, Ropa Médica',
        tags: 'Kimono, Protector, Barrera'
    },
    77: {
        id: 77,
        title: 'Dispensador de Agua',
        price: 65.00,
        description: 'Dispensador de agua electrónico, botón touch para dispensar agua con doble motor para mas velocidad, ideal para tu garrafón de agua, muy practico, recargable, facil instalación.',
        rating: 4,
        reviews: 67,
        images: [],
        categories: 'Equipamiento, Oficina',
        tags: 'Dispensador, Agua, Electrónico'
    },
    78: {
        id: 78,
        title: 'Dispensador de Toalla',
        price: 28.50,
        description: 'Diseñado para la dispensación controlada de toallas de papel, usado principalmente en baños, cocinas o áreas de trabajo donde se requiere higiene.',
        rating: 4,
        reviews: 78,
        images: [],
        categories: 'Equipamiento, Higiene',
        tags: 'Dispensador, Toalla, Papel'
    },
    79: {
        id: 79,
        title: 'Dispensador en Rollo',
        price: 22.99,
        description: 'Diseñado para suministrar toalla de papel en rollo, ideal para el secado de manos en baños, cocinas o áreas industriales.',
        rating: 4,
        reviews: 56,
        images: [],
        categories: 'Equipamiento, Higiene',
        tags: 'Dispensador, Rollo, Toalla'
    },
    80: {
        id: 80,
        title: 'Gafa de Seguridad',
        price: 9.75,
        description: 'Para la protección ocular en diversas actividades laborales, industriales, médicas o de laboratorio. Protección contra salpicaduras químicas, polvo o partículas.',
        rating: 4,
        reviews: 134,
        images: [],
        categories: 'Protección Personal, EPP',
        tags: 'Gafa, Seguridad, Ocular'
    },
    81: {
        id: 81,
        title: 'Lentes de Seguridad',
        price: 12.25,
        description: 'Patillas ajustables. Se usan para proteger los ojos de distintos peligros en el entorno. Protección contra impacto evitando partículas, astillas de madera, metal o fragmentos de vidrio golpeen los ojos, protección contra salpicaduras químicas y protección contra polvo y escombros.',
        rating: 5,
        reviews: 189,
        images: [],
        categories: 'Protección Personal, EPP',
        tags: 'Lentes, Seguridad, Protección'
    },
    82: {
        id: 82,
        title: 'Basurero Rojo',
        price: 35.00,
        description: 'Un basurero para residuos bioinfecciosos está diseñado para desechar materiales que puedan transmitir enfermedades (como gasas con sangre, agujas, guantes contaminados, etc.). Obligatorio en hospitales, clínicas, laboratorios y lugares donde se generen desechos biológicos.',
        rating: 4,
        reviews: 67,
        images: [],
        categories: 'Equipamiento, Hospitalario',
        tags: 'Basurero, Rojo, Bioinfeccioso'
    },
    83: {
        id: 83,
        title: 'Recipiente Rojo',
        price: 28.75,
        description: 'Para almacenamiento específico de elementos de uso quirúrgico o de curación como gasas, baja lenguas, algodón, aplicadores, agujas, jeringas, guantes.',
        rating: 4,
        reviews: 45,
        images: [],
        categories: 'Equipamiento, Hospitalario',
        tags: 'Recipiente, Rojo, Quirúrgico'
    },
    84: {
        id: 84,
        title: 'Jeringas Desechables',
        price: 5.99,
        description: 'Diseñadas para ofrecer la máxima precisión y comodidad en cada uso. Asegura una punción suave y reducir al mínimo el dolor en el paciente. Estéril y desechable.',
        rating: 5,
        reviews: 278,
        images: [],
        categories: 'Insumos Médicos, Desechables',
        tags: 'Jeringas, Desechables, Estériles'
    },
    85: {
        id: 85,
        title: 'Gasa Estéril',
        price: 8.25,
        description: 'Diseñada para usarse directamente sobre heridas abiertas o durante procedimientos médicos y quirúrgicos; Permite limpiar, cubrir y proteger heridas, absorber fluidos y aplicar medicamentos sin riesgo de contaminación.',
        rating: 5,
        reviews: 189,
        images: [],
        categories: 'Curación, Insumos Médicos',
        tags: 'Gasa, Estéril, Quirúrgica'
    },
    86: {
        id: 86,
        title: 'Gasa Tejida',
        price: 7.50,
        description: 'Tejido entrelazado que permite el paso de aire y la absorción de líquidos; se utiliza en la limpieza y protección de heridas, aplicación de medicamentos y absorción de fluidos.',
        rating: 4,
        reviews: 156,
        images: [],
        categories: 'Curación, Insumos Médicos',
        tags: 'Gasa, Tejida, Absorbente'
    },
    87: {
        id: 87,
        title: 'Mascarilla de Niños',
        price: 9.99,
        description: 'Diseñadas para reducir la propagación de partículas de la persona que las usa. Existen diferentes modelos y diseños.',
        rating: 4,
        reviews: 167,
        images: [],
        categories: 'Protección Personal, Mascarillas',
        tags: 'Mascarilla, Niños, Protección'
    }
};