export const productsData = {
    0: {
        id: 0,
        title: 'Lancetas',
        price: 2800,
        description: 'Permite realizar una punción en la piel para obtener sangre, también usado en las estéticas para sacar espinillas y puntos negros. Caja con 100 unidades.',
        rating: 4,
        reviews: 89,
        review: "Excelente producto para uso en mi clínica estética. Las lancetas son muy precisas y vienen bien empacadas. Muy recomendadas para procedimientos de extracción.",
        images: ['../img/img1/producto1.png'],
        categories: 'Insumos Médicos, Desechables',
        tags: 'Lancetas, Estética, Punción',
        colors: ['Blanco'],
        characteristics: 'Estériles, aguja ultra fina 30G, profundidad controlada 1.5mm, seguridad con tapa protectora, material hipoalergénico',
        wholesale: true,
        discount: false
    },
    1: {
        id: 1,
        title: 'Gel Ultrasonido',
        price: 11000,
        description: 'Gel que contribuye a la lubricación durante el ultrasonido u otros procedimientos. También es usado en la depilación laser, radiofrecuencia o ultrasonidos. No daña el transductor, se extiende fácil y uniformemente, no irrita la piel. Cantidad 5 litros.',
        rating: 4,
        reviews: 124,
        review: "El gel tiene excelente consistencia y se extiende muy bien. Lo uso para depilación láser y ultrasonido, rinde bastante. No irrita la piel de mis pacientes.",
        images: ['../img/img1/producto2.png'],
        categories: 'Insumos Médicos, Estética',
        tags: 'Ultrasonido, Gel, Lubricante',
        colors: ['Blanco'],
        characteristics: 'Base acuosa, hipoalergénico, pH neutro 7.0, no mancha, transparente, conductividad optimizada para equipos médicos',
        wholesale: false,
        discount: true
    },
    2: {
        id: 2,
        title: 'Micropore 3M',
        price: 2750,
        description: 'Cinta suave y amable con la piel, de papel que se usa para curar las heridas y asegurar los tubos médicos y apósitos. Tamaño: 2,5 x 9,1 mts.',
        rating: 5,
        reviews: 203,
        review: "La calidad 3M es garantía. Esta cinta es perfecta para piel sensible, se adhiere bien pero no lastima al retirarla. Indispensable en mi consultorio.",
        images: ['../img/img1/producto3.png'],
        categories: 'Curación, Insumos Médicos',
        tags: 'Micropore, 3M, Cinta Médica',
        colors: ['Blanco'],
        characteristics: 'Adhesivo hipoalergénico, transpirable, poros de 0.65mm, resistencia a la humedad, ancho 2.5cm, largo 9.1m',
        wholesale: false,
        discount: true
    },
    3: {
        id: 3,
        title: 'Bolsas para Esterilizar',
        price: "Precio a cotizar", 
        description: 'Papel grado médico, indicado para el proceso de esterilización, diferentes tamaños disponibles. Caja con 200 unidades.',
        rating: 4,
        reviews: 67,
        review: "Uso estas bolsas para esterilizar instrumental quirúrgico. Los indicadores químicos funcionan perfecto y el papel es resistente al proceso de autoclave.",
        images: ['../img/img1/producto4.png'],
        categories: 'Esterilización, Insumos Médicos',
        tags: 'Esterilización, Bolsas, Médico',
        colors: ['Blanco'],
        characteristics: 'Papel crepado grado médico, indicador químico integrado, sellado térmico a 121°C, resistente a autoclave, tamaños 10x15cm a 30x40cm',
        wholesale: false,
        discount: false
    },
    4: {
        id: 4,
        title: 'Rollo para Esterilizar',
        price: "Precio a cotizar",
        description: 'Rollo de bolsas para esterilización de diferentes instrumentos, papel grados médico, cada rollo contiene 200 metros, hay de diferentes tamaños.',
        rating: 4,
        reviews: 45,
        review: "El rollo es muy práctico porque puedo cortar el tamaño exacto que necesito. Excelente relación precio-cantidad, rinde muchísimo.",
        images: ['../img/img1/producto5.png'],
        categories: 'Esterilización, Insumos Médicos',
        tags: 'Esterilización, Rollo, Papel Médico',
        colors: ['Blanco'],
        characteristics: 'Papel kraft médico 200 metros, ancho 50cm, resistencia a vapor 134°C, poroso para penetración de esterilizante, libre de toxinas',
        wholesale: false,
        discount: false
    },
    5: {
        id: 5,
        title: 'Barrera Adhesiva',
        price: 6800,
        description: 'Film adhesivo que se emplea para no dejar residuos de ningún tipo sea la superficie que sea. Desechable, fácil de aplicar y quitar, no deja ningún residuo.',
        rating: 4,
        reviews: 78,
        review: "Protege muy bien las superficies de trabajo y equipos. Se adhiere perfectamente y al retirarlo no deja nada pegajoso. Muy conveniente para mantener la higiene.",
        images: ['../img/img1/producto6.png'],
        categories: 'Protección, Insumos Médicos',
        tags: 'Barrera, Adhesiva, Protección',
        colors: ['Azul', 'Transparente'],
        characteristics: 'Film polipropileno 25 micras, adhesivo de baja adherencia, ancho 45cm, transparente/azul, resistente a líquidos, no deja residuos',
        wholesale: true,
        discount: false
    },
    6: {
        id: 6,
        title: 'Pads de Yodo',
        price: 3500,
        description: 'Ideal para preparación de la piel antiséptica y otros procedimientos invasivos menores. Almohadilla impregnada con povidona yodada al 10%. Caja con 100 unidades.',
        rating: 5,
        reviews: 156,
        review: "Los pads vienen bien impregnados de yodo, no gotean. Son perfectos para preparación preoperatoria y limpieza de heridas. Muy higiénicos al venir empacados individualmente.",
        images: ['../img/img1/producto7.png'],
        categories: 'Antisépticos, Curación',
        tags: 'Yodo, Antiséptico, Pads',
        colors: ['Blanco'],
        characteristics: 'Povidona yodada 10%, almohadilla no tejida 6x6cm, empaque individual estéril, acción bactericida rápida, efectivo contra hongos y virus',
        wholesale: true,
        discount: false
    },
    7: {
        id: 7,
        title: 'Pads de Alcohol',
        price: "Precio a cotizar",
        description: 'Toallitas impregnadas en alcohol de 70%, para desinfectar heridas, cortes o áreas pequeñas antes de realizar un procedimiento. Caja con 100 unidades.',
        rating: 4,
        reviews: 189,
        review: "Siempre los tengo a mano en mi consultorio. Son muy prácticos para desinfección rápida antes de inyecciones o procedimientos menores. Buena saturación de alcohol.",
        images: ['../img/img1/producto8.png'],
        categories: 'Desinfección, Curación',
        tags: 'Alcohol, Desinfectante, Pads',
        colors: ['Blanco'],
        characteristics: 'Alcohol isopropílico 70%, tamaño 5x5cm, material no tejido, empaque individual, secado rápido, acción desinfectante inmediata',
        wholesale: true,
        discount: false
    },
    8: {
        id: 8,
        title: 'Suctor de Saliva',
        price: 2800,
        description: 'Conocido como eyector de saliva o suctor. Su función es succionar el exceso de saliva, agua o sangre, se dobla fácilmente, no tiene memoria al momento de doblarse, longitud de 15cm. Paquete con 100 unidades.',
        rating: 4,
        reviews: 92,
        review: "Como dentista, estos suctores son esenciales en mi trabajo diario. Se doblan sin problema y la succión es eficiente. Buena calidad por el precio.",
        images: ['../img/img1/producto9.png'],
        categories: 'Odontología, Insumos Médicos',
        tags: 'Suctor, Saliva, Odontología',
        colors: ['Blanco'],
        characteristics: 'Polipropileno flexible, longitud 15cm, diámetro 8mm, punta redondeada, esterilizable, no reactivo con saliva',
        wholesale: true,
        discount: false
    },
    9: {
        id: 9,
        title: 'Cubre Zapatos',
        price: 3500,
        description: 'Protegen el calzado, evitando la transmisión de gérmenes y disminuyen la cantidad de suciedad. Hecho de tela no tejida y con antideslizante. Paquete con 100 unidades.',
        rating: 4,
        reviews: 134,
        review: "Muy útiles para mantener las áreas estériles limpias. El material antideslizante es un plus importante para la seguridad. Talla universal que se ajusta bien.",
        images: ['../img/img1/producto10.png'],
        categories: 'Protección Personal, EPP',
        tags: 'Cubre Zapatos, Protección, Hospital',
        colors: ['Blanco'],
        characteristics: 'Tela SMS 35gsm, suela antideslizante texturizada, elástico en tobillo, talla única 28-46, resistencia a líquidos, peso 8g por unidad',
        wholesale: true,
        discount: false
    },
    10: {
        id: 10,
        title: 'Bata sin Manga',
        price: 3500,
        description: 'Bata de un solo uso fabricada con tela no tejida SMS, sin mangas y con cierre trasero de cintas para atar al cuello y a la cintura. Paquete con 10 unidades. Talla: Única.',
        rating: 4,
        reviews: 167,
        review: "Perfectas para procedimientos que no requieren bata quirúrgica completa. El material SMS es resistente y transpirable. Buen ajuste con las cintas.",
        images: ['../img/img1/producto11.png'],
        categories: 'Ropa Médica, Protección',
        tags: 'Bata, Desechable, Médico',
        colors: ['Azul', 'Negro'],
        characteristics: 'Tela SMS 40gsm, cintas de polipropileno, apertura posterior, nivel de protección AAMI 1, resistencia a líquidos, talla única 110x140cm',
        wholesale: true,
        discount: false
    },
    11: {
        id: 11,
        title: 'Bata Manga Larga',
        price: 4000,
        description: 'Bata de un solo uso fabricada con tela no tejida SMS, mangas larga, con puño de elástico o de algodón y con cierre trasero de cintas para atar al cuello y a la cintura. Paquete con 10 unidades. Talla: Única.',
        rating: 5,
        reviews: 198,
        review: "Mayor protección con las mangas largas. Los puños elásticos ajustan bien y evitan que se suban. Material resistente que no se rompe fácilmente durante el uso.",
        images: ['../img/img1/producto12.png'],
        categories: 'Ropa Médica, Protección',
        tags: 'Bata, Manga Larga, Protección',
        colors: ['Azul', 'Negro'],
        characteristics: 'Tela SMS 45gsm, mangas con puños elásticos, protección AAMI 2, barrera contra fluidos, refuerzos en costuras, talla única 120x150cm',
        wholesale: true,
        discount: false
    },
    12: {
        id: 12,
        title: 'Sábana sin Elástico',
        price: 3500,
        description: 'Superficie suave, resistente a líquidos, no estéril y de un solo uso, hecha de polipropileno (no tejida), diseñada para su uso en mesas de masaje, camillas y cobertor en salones de belleza. Paquete con 10 unidades.',
        rating: 4,
        reviews: 112,
        review: "Las uso en mi spa para las camillas de masaje. Son resistentes al aceite y muy higiénicas. A mis clientes les gusta la textura suave del material.",
        images: ['../img/img1/producto13.png'],
        categories: 'Estética, Insumos',
        tags: 'Sábana, Estética, Masaje',
        colors: ['Azul', 'Negro'],
        characteristics: 'Polipropileno 60gsm, tamaño 140x180cm, tratamiento hidrófugo, superficie no tejida, resistente a aceites, suave al contacto',
        wholesale: true,
        discount: false
    },
    13: {
        id: 13,
        title: 'Cubre Camilla',
        price: 4000,
        description: 'Superficie suave, tiene elástico en los bordes, resistente a líquidos, no estéril y de un solo uso, hecha de polipropileno (no tejida), diseñada para su uso en mesas de masaje, camillas y cobertor en salones de belleza. Paquete con 10 unidades.',
        rating: 4,
        reviews: 145,
        review: "El elástico en los bordes es genial, mantiene todo en su lugar durante los tratamientos. No se corre ni se arruga. Muy práctico para cambiar rápido entre clientes.",
        images: ['../img/img1/producto14.png'],
        categories: 'Estética, Insumos Médicos',
        tags: 'Cubre Camilla, Estética, Protección',
        colors: ['Azul', 'Negro'],
        characteristics: 'Polipropileno 65gsm, elástico perimetral 1.5cm, tamaño 140x180cm, resistencia a líquidos, ajuste seguro hasta 90cm ancho',
        wholesale: true,
        discount: false
    },
    14: {
        id: 14,
        title: 'Cubre Barba',
        price: 3500,
        description: 'Se usa para cubrir el vello facial y evitar que el pelo suelto caiga en un espacio de trabajo, retiene la caída del vello facial durante la manipulación de alimentos u otros artículos. Se usa en laboratorios, industria alimentaria, labores de limpieza. Paquete con 100 unidades.',
        rating: 4,
        reviews: 87,
        review: "Los uso en mi restaurante para cumplir con normas de higiene. Son cómodos y los empleados no tienen problema en usarlos. Buen material que respira bien.",
        images: ['../img/img1/producto15.png'],
        categories: 'Protección Personal, EPP',
        tags: 'Cubre Barba, Protección, Alimentos',
        colors: ['Blanco'],
        characteristics: 'Tela no tejida 25gsm, diseño tipo máscara, elástico ajustable, cubre barba y bigote, transpirable, cumple normas HACCP',
        wholesale: true,
        discount: false
    },
    15: {
        id: 15,
        title: 'Babero Servitoallas',
        price: 5000,
        description: 'Utilizada para hacer manicure como paño para cualquier derrame, para pedicure como separador de dedos de los pies, también para tinte y cortar el pelo en la parte trasera de la cabeza, cobertor de cabecera, protegiendo de todo tipo de contaminantes, y los odontólogos como baberos. Paquete de 125 unidades.',
        rating: 4,
        reviews: 176,
        review: "Súper versátiles! Las uso en mi salón de belleza para múltiples cosas. Absorben muy bien y la variedad de colores permite organizar mejor. Excelente compra.",
        images: ['../img/img1/producto17.png'],
        categories: 'Estética, Odontología',
        tags: 'Babero, Servitoallas, Estética',
        colors: ['Rosa', 'Blanco', 'Negro', 'Verde', 'Turquesa', 'Morado', 'Rojo', 'Amarillo', 'Naranja', 'Azul'],
        characteristics: 'Papel crepado 2 capas, tamaño 33x46cm, alta absorbencia 400ml/m², resistencia humedad, colores diferenciados, libre de latex',
        wholesale: true,
        discount: false
    },
    16: {
        id: 16,
        title: 'Capucha Protectora',
        price: 5500,
        description: 'Aisla el pelo y cubre totalmente la cabeza en tareas con mayor riesgo de contaminación o infección. Mantiene la higiene y la seguridad. Paquete con 100 unidades.',
        rating: 4,
        reviews: 98,
        review: "Perfectas para procedimientos que requieren mayor protección. Cubren completamente el cabello y son cómodas de usar durante largos periodos.",
        images: ['../img/img1/producto16.png'],
        categories: 'Protección Personal, EPP',
        tags: 'Capucha, Protección, Higiene',
        colors: ['Blanco'],
        characteristics: 'Polietileno 25 micras, diseño tipo capucha, sello elástico facial, transpirable, protección completa cabello y cuello, talla única',
        wholesale: true,
        discount: false
    },
    17: {
        id: 17,
        title: 'Gorro Clip o Acordeón',
        price: 2500,
        description: 'Para evitar la caída de cabello, viene en forma de gusanito o acordeón, varios colores disponibles. Paquete de 100 unidades.',
        rating: 4,
        reviews: 123,
        review: "Los gorros tipo acordeón son muy prácticos. Se ajustan bien a diferentes tamaños de cabeza y los colores ayudan a diferenciar áreas en mi clínica.",
        images: ['../img/img1/producto18.png'],
        categories: 'Protección Personal, Estética',
        tags: 'Gorro, Acordeón, Protección',
        colors: ['Rosa', 'Celeste', 'Negro'],
        characteristics: 'Polipropileno no tejido, diseño acordeón extensible, talla única 50-60cm, elástico interno, peso 5g, colores diferenciados por área',
        wholesale: true,
        discount: false
    },
    18: {
        id: 18,
        title: 'Gorro Malla',
        price: 3500,
        description: 'Para evitar la caída del cabello, ideal para hoteles, restaurantes, cafeterías, y tareas de limpieza. Paquete con 100 unidades.',
        rating: 4,
        reviews: 156,
        review: "En mi cocina industrial son obligatorios. Estos gorros de malla son cómodos y permiten que el cuero cabelludo respire. No causan incomodidad durante el turno.",
        images: ['../img/img1/producto19.png'],
        categories: 'Protección Personal, Alimentos',
        tags: 'Gorro Malla, Protección, Alimentos',
        colors: ['Blanco', 'Negro'],
        characteristics: 'Poliéster mesh, malla 1.5mm, diseño tipo redecilla, talla ajustable, lavable reusable, cumple normas alimentarias FDA',
        wholesale: true,
        discount: false
    },
    19: {
        id: 19,
        title: 'Aceite para Masaje',
        price: "Precio a cotizar",
        description: 'Aceite a base de uva y extractos naturales, no contiene aceite mineral, es decir proveniente del petróleo. Tamaños: 250ml, litro o galón.',
        rating: 5,
        reviews: 234,
        review: "El mejor aceite que he usado! No es grasoso, se absorbe bien y el aroma es muy agradable. Mis clientes siempre comentan lo suave que deja la piel.",
        images: ['../img/img1/producto20.png'],
        categories: 'Estética, Masajes',
        tags: 'Aceite, Masaje, Natural',
        colors: ['Blanco'],
        characteristics: 'Base aceite de uva, extractos naturales, pH 5.5, no comedogénico, absorción rápida, libre de parabenos y mineral oil',
        wholesale: false,
        discount: false
    },
    20: {
        id: 20,
        title: 'Aplicadores Largos',
        price: 1000,
        description: 'Sirve para aplicar cualquier tipo de sustancia, limpia, desinfecta y absorbe, no estéril, de 6 pulgadas. Paquete con 100 unidades.',
        rating: 4,
        reviews: 87,
        review: "Los aplicadores largos son perfectos para alcanzar áreas difíciles. La punta de algodón es firme pero no raspa. Muy útiles en curaciones.",
        images: ['../img/img1/producto21.png'],
        categories: 'Insumos Médicos, Desechables',
        tags: 'Aplicadores, Largos, Desechables',
        colors: ['Blanco'],
        characteristics: 'Vara de madera 15cm, punta algodón puro, diámetro punta 8mm, no estéril, absorción media, empaque individual',
        wholesale: false,
        discount: false
    },
    21: {
        id: 21,
        title: 'Aplicador Corto',
        price: 500,
        description: 'Sirve para aplicar cualquier tipo de sustancia, limpia, desinfecta y absorbe, no estéril, de 3 pulgadas. Paquete con 100 unidades.',
        rating: 4,
        reviews: 76,
        review: "Ideales para aplicaciones de precisión. Los uso mucho en estética para aplicar productos en áreas pequeñas. Buena absorción y precio accesible.",
        images: ['../img/img1/producto22.png'],
        categories: 'Insumos Médicos, Desechables',
        tags: 'Aplicadores, Cortos, Desechables',
        colors: ['Blanco'],
        characteristics: 'Vara de madera 7.5cm, punta algodón compacto, diámetro punta 6mm, precisión aplicaciones, empaque a granel, peso ligero',
        wholesale: false,
        discount: false
    },
    22: {
        id: 22,
        title: 'Venda Coban',
        price: 1000,
        description: 'Venda elástica autoadherente, se fija sobre si misma, se usa para lesiones, esguinces y para proteger apósitos y dispositivos. Tamaño 5cm x 4.5m.',
        rating: 5,
        reviews: 145,
        review: "La venda coban es increíble! No necesita clips ni alfileres, se adhiere sola. Perfecta para vendajes deportivos y post-operatorios. Los colores son un plus.",
        images: ['../img/img1/producto23.png'],
        categories: 'Curación, Ortopedia',
        tags: 'Venda, Coban, Elástica',
        colors: ['Negro', 'Morado', 'Azul', 'Rojo'],
        characteristics: 'Material cohesivo latex-free, ancho 5cm, largo 4.5m, elasticidad 150%, autoadherente, poroso transpirable, colores diferenciados',
        wholesale: true,
        discount: false
    },
    23: {
        id: 23,
        title: 'Gasa No Tejida',
        price: "Precio a cotizar",
        description: '100% algodonada, extra absorbente, bajo en pelusa, libre de látex, no tejida, de un solo uso, no estéril, paquete de 200 unidades. Diferentes tamaños disponibles: 2x2, 3x3, 4x4.',
        rating: 4,
        reviews: 167,
        review: "Excelente absorción y no deja pelusa en las heridas. Son muy suaves y no se deshacen al usarlas. Buena relación calidad-precio para uso diario.",
        images: ['../img/img1/producto24.png'],
        categories: 'Curación, Insumos Médicos',
        tags: 'Gasa, No Tejida, Absorbente',
        colors: ['Blanco'],
        characteristics: 'Algodón 100% hidrófilo, baja pelusidad, tamaño 10x10cm, absorción 12g/g, libre de latex, empaque a granel',
        wholesale: true,
        discount: false
    },
    24: {
        id: 24,
        title: 'Esterilix Equipos',
        price: "Precio a cotizar",
        description: 'Desinfectante de alto nivel de uso directo, formulada para la eliminación de todo tipo de microorganismos, patógenos.',
        rating: 5,
        reviews: 89,
        review: "Uso Esterilix para desinfectar todos mis equipos médicos. Es muy efectivo y no daña los instrumentos. Me da confianza en la eliminación de patógenos.",
        images: ['../img/img1/producto25.png'],
        categories: 'Limpieza, Desinfección',
        tags: 'Esterilix, Desinfectante, Equipos',
        colors: ['Blanco'],
        characteristics: 'Glutaraldehído 2.4%, acción esporicida en 10h, compatibilidad metales, uso directo sin diluir, efectivo TB, HIV, HBV',
        wholesale: true,
        discount: false
    },
    25: {
        id: 25,
        title: 'Esterilix Superficie',
        price: 5500,
        description: 'Desinfectante ya diluido de aplicación directa con aspersión, para facilitar el uso ya que no requiere enjuague y es de fácil aplicación, especialmente formulada para la eliminación y prevención de contaminación biológica de microorganismos patógenos.',
        rating: 4,
        reviews: 112,
        review: "Lo uso entre cada paciente para desinfectar superficies. No mancha, no deja residuos y el spray facilita mucho la aplicación. Seca rápido.",
        images: ['../img/img1/producto26.png'],
        categories: 'Limpieza, Desinfección',
        tags: 'Esterilix, Superficie, Desinfectante',
        colors: ['Blanco'],
        characteristics: 'Amonios cuaternarios 0.5%, listo para usar, acción bactericida en 5min, spray 500ml, no corrosivo, secado rápido 3min',
        wholesale: true,
        discount: false
    },
    26: {
        id: 26,
        title: 'Esterilix X-7',
        price: 10000,
        description: 'Indicado para la desinfección en frío de instrumental, equipo medico u superficie.',
        rating: 4,
        reviews: 78,
        review: "Excelente para instrumental que no puede ir al autoclave. La desinfección en frío es muy efectiva y no corroe los metales. Muy recomendado.",
        images: ['../img/img1/producto27.png'],
        categories: 'Limpieza, Desinfección',
        tags: 'Esterilix, X-7, Desinfección',
        colors: ['Blanco'],
        characteristics: 'Glutaraldehído 3.4%, desinfección nivel alto, tiempo activación 30min, vida útil 28 días, compatible acero inoxidable',
        wholesale: true,
        discount: false
    },
    27: {
        id: 27,
        title: 'Cleaner 256',
        price: 2500,
        description: 'Limpiador desinfectante concentrado de uso profesional y de amplio espectro que combina tres principios activos: aldehídos, alcoholes y amonios cuaternarios de quinta generación. Rinde hasta 256 veces su presentación.',
        rating: 5,
        reviews: 134,
        review: "Increíble rendimiento! Un litro me dura meses. La capacidad de dilución es real y no pierde efectividad. Ahorro significativo para mi clínica.",
        images: ['../img/img1/producto28.png'],
        categories: 'Limpieza, Desinfección',
        tags: 'Cleaner, 256, Concentrado',
        colors: ['Blanco'],
        characteristics: 'Concentrado triple acción, dilución 1:256, amonios cuaternarios 5G, efectivo virus enveloped, rendimiento 256L por litro',
        wholesale: true,
        discount: false
    },
    28: {
        id: 28,
        title: 'Detercel Enzimático',
        price: 14500,
        description: 'Detergente multienzimático líquido, diseñado para la limpieza de instrumental, equipo médico u odontológico. Contiene proteasas, amilasas y lipasas, es un detergente no iónico que ha sido formulado con antioxidantes para evitar oxidación de instrumental y equipos en los que se emplee.',
        rating: 4,
        reviews: 96,
        review: "La limpieza enzimática es superior. Elimina materia orgánica que otros detergentes no pueden. Además protege el instrumental de la oxidación. Vale la pena.",
        images: ['../img/img1/producto29.png'],
        categories: 'Limpieza, Enzimático',
        tags: 'Detercel, Enzimático, Detergente',
        colors: ['Blanco'],
        characteristics: 'Enzimas proteasa/amilasa/lipasa, pH neutro 7.2, antioxidantes integrados, dilución 1:200, baja espuma, protección anticorrosión',
        wholesale: true,
        discount: false
    },
    29: {
        id: 29,
        title: 'Neutralizador de Olor',
        price: 2000,
        description: 'Neutralizan olores no deseados, como el tabaco, materia en descomposición y la humedad. Los elimina por completo, dejando aire fresco, limpio y natural.',
        rating: 4,
        reviews: 145,
        review: "No solo tapa los olores, realmente los neutraliza. Lo uso en áreas de curación y funciona perfecto. No deja olor artificial fuerte, solo frescura.",
        images: ['../img/img1/producto30.png'],
        categories: 'Limpieza, Ambientadores',
        tags: 'Neutralizador, Olor, Ambientador',
        colors: ['Blanco'],
        characteristics: 'Tecnología encapsulación olores, base zeolita natural, duración 30 días, área cobertura 20m², libre de CFC, aroma fresco natural',
        wholesale: true,
        discount: false
    },
    30: {
        id: 30,
        title: 'Cloridex',
        price: 8000,
        description: 'Puede ser usado como limpiador de manos. Como antiséptico quirúrgico para preparar la piel del paciente preoperatorio. Como limpiador de heridas cutáneas y limpiador de piel en general (acné, foliculitis de la barba y otras infecciones de la piel).',
        rating: 5,
        reviews: 223,
        review: "Producto versátil y efectivo. Lo uso tanto para lavado quirúrgico como para limpieza de heridas. No reseca la piel y tiene buen efecto antibacteriano.",
        images: ['../img/img1/producto31.png'],
        categories: 'Antisépticos, Higiene',
        tags: 'Cloridex, Antiséptico, Quirúrgico',
        colors: ['Blanco'],
        characteristics: 'Clorhexidina 4%, solución jabonosa, acción residual 6h, efectivo Gram+ y Gram-, pH balanceado, emolientes piel',
        wholesale: true,
        discount: false
    },
    31: {
        id: 31,
        title: 'Agua Destilada',
        price: 2500,
        description: 'Es resultado de un proceso de purificación por el cual se eliminan una gran cantidad de impurezas características en el agua doméstica y se eliminan iones.',
        rating: 4,
        reviews: 178,
        review: "Indispensable para autoclave y equipos médicos. La pureza es excelente y evita que se forme sarro en mis equipos. Buen precio por galón.",
        images: ['../img/img1/producto32.png'],
        categories: 'Insumos Médicos, Laboratorio',
        tags: 'Agua, Destilada, Purificada',
        colors: ['Blanco'],
        characteristics: 'Pureza 99.9%, conductividad <5µS/cm, libre iones, pH 7.0, envase galón HDPE, uso autoclave y equipos médicos',
        wholesale: true,
        discount: false
    },
    32: {
        id: 32,
        title: 'Agua Oxigenada',
        price: 3500,
        description: 'Se utiliza para productos de limpieza y de cuidado personal como: Colorantes, blanqueadores, quita manchas, limpiador de baño, entre otros.',
        rating: 4,
        reviews: 156,
        review: "Muy útil para limpieza de heridas y desinfección. También la uso para blanquear superficies. Buena concentración y rendimiento.",
        images: ['../img/img1/producto33.png'],
        categories: 'Limpieza, Cuidado Personal',
        tags: 'Agua, Oxigenada, Blanqueador',
        colors: ['Blanco'],
        characteristics: 'Peróxido hidrógeno 10vol, acción oxidante, desinfectante heridas, blanqueador natural, envase PET oscuro, estabilizado',
        wholesale: true,
        discount: false
    },
    33: {
        id: 33,
        title: 'Alcohol Líquido',
        price: 9500,
        description: 'Incoloro, volátil, con olor característico. Es muy usado como disolventes, se usa en mezclas anticongelantes, como combustible, como antiséptico, y muchas funciones más.',
        rating: 4,
        reviews: 189,
        review: "Alcohol de buena calidad y concentración. Lo uso para desinfección de superficies y equipos. El galón rinde mucho para uso profesional.",
        images: ['../img/img1/producto34.png'],
        categories: 'Antisépticos, Limpieza',
        tags: 'Alcohol, Líquido, Antiséptico',
        colors: ['Blanco'],
        characteristics: 'Etanol 96°, pureza USP, densidad 0.789g/ml, punto ebullición 78°C, envase galón, múltiples usos médico-industriales',
        wholesale: true,
        discount: false
    },
    34: {
        id: 34,
        title: 'Lavaplatos Multiacción',
        price: 4200,
        description: 'La Crema Lavaplatos Multiacción es un producto diseñado para remover suciedad de vajillas y otros implementos utilizados comúnmente en el área de cocina, mediante el lavado manual. Contiene microabrasivos que facilitan la remoción de grasas a la vez que en su formulación se incluyen agentes humectantes para evitar resecar la piel.',
        rating: 4,
        reviews: 234,
        review: "Corta la grasa muy bien y no reseca las manos. Los microabrasivos ayudan con la suciedad difícil. Buen rendimiento y aroma agradable.",
        images: ['../img/img1/producto35.png'],
        categories: 'Limpieza, Cocina',
        tags: 'Lavaplatos, Multiacción, Limpieza',
        colors: ['Blanco'],
        characteristics: 'Microabrasivos sílice, agentes humectantes glicerina, pH neutro 7.5, acción desengrasante, protección dermatológica, aroma limón',
        wholesale: false,
        discount: false
    },
    35: {
        id: 35,
        title: 'Alcohol en Gel 300ml',
        price: 3500,
        description: 'Reconocido por su rápida actividad contra una amplia gama de virus, bacterias y virus, hongos, no requiere enjuague, fácil aplicación.',
        rating: 5,
        reviews: 267,
        review: "El gel tiene buena consistencia, no queda pegajoso ni reseca las manos. Lo tengo en todas las áreas de mi consultorio. Muy práctico el dispensador.",
        images: ['../img/img1/producto36.png'],
        categories: 'Higiene, Antisépticos',
        tags: 'Alcohol, Gel, Desinfectante',
        colors: ['Blanco'],
        characteristics: 'Etanol 70%, gel carbopol, humectantes pantenol, viscosidad 3000cps, acción rápida 30s, envase 300ml con dispensador',
        wholesale: true,
        discount: false
    },
    36: {
        id: 36,
        title: 'Alcohol en Gel',
        price: "Agotado",
        description: 'Reconocido por su rápida actividad contra una amplia gama de virus, bacterias y virus, hongos, no requiere enjuague, fácil aplicación.',
        rating: 5,
        reviews: 189,
        review: "Compro la presentación grande para rellenar dispensadores. Muy económico así y la calidad es la misma. Excelente para uso intensivo en clínicas.",
        images: ['../img/img1/producto37.png'],
        categories: 'Higiene, Antisépticos',
        tags: 'Alcohol, Gel, Desinfectante',
        colors: ['Blanco'],
        characteristics: 'Etanol 70% grado médico, gelificación carbomer, emolientes piel, presentación 5L, rendimiento 5000 aplicaciones, recargable',
        wholesale: false,
        discount: false
    },
    37: {
        id: 37,
        title: 'Jabón Líquido',
        price: "Agotado",
        description: 'El Jabón Líquido para Manos está diseñado para la limpieza y humectación de las manos, sin provocar resequedad después de su aplicación. Disponible en diferentes cromas y neutro.',
        rating: 4,
        reviews: 278,
        review: "Muy suave con la piel, no reseca aunque te laves las manos muchas veces al día. Los diferentes aromas son agradables y no muy fuertes. Buen rendimiento.",
        images: ['../img/img1/producto38.png'],
        categories: 'Higiene, Cuidado Personal',
        tags: 'Jabón, Líquido, Manos',
        colors: ['Blanco'],
        characteristics: 'Base tensioactivos suaves, pH 5.5, humectantes aloe vera, presentación 1L, aromas variados, rendimiento 800 lavados',
        wholesale: false,
        discount: false
    },
    38: {
        id: 38,
        title: 'Cinta Testigo',
        price: 3200,
        description: 'Es utilizado principalmente en procesos de esterilización y control de calidad. Su función básica es servir como indicador químico que verifica si ha sido expuesto a un proceso de esterilización (por ejemplo, vapor, óxido de etileno o plasma). Cambia de color al ser sometida a las condiciones adecuadas.',
        rating: 4,
        reviews: 67,
        review: "Indispensable para verificar que el autoclave funciona correctamente. El cambio de color es claro y fácil de identificar. Dá seguridad en la esterilización.",
        images: ['../img/img1/producto39.png'],
        categories: 'Esterilización, Control Calidad',
        tags: 'Cinta, Testigo, Esterilización',
        colors: ['Blanco'],
        characteristics: 'Indicador químico vapor, cambio color beige a negro, temperatura 121°C, tiempo 15min, ancho 1.5cm, rollo 18m',
        wholesale: false,
        discount: false
    },
    39: {
        id: 39,
        title: 'Mascarilla KN95',
        price: 3800,
        description: 'Tira de nariz ajustable, evita la entrada de aire contaminado, 5 capas, varios colores disponibles. Caja de 10 o 20 unidades.',
        rating: 5,
        reviews: 345,
        review: "Excelente ajuste y filtración. Las 5 capas dan muy buena protección. La tira nasal se moldea bien y no se afloja. Los colores permiten combinar o diferenciar.",
        images: ['../img/img1/producto40.png'],
        categories: 'Protección Personal, Mascarillas',
        tags: 'KN95, Mascarilla, Protección',
        colors: ['Blanco', 'Rosa', 'Negro', 'Verde', 'Azul', 'Naranja', 'Amarillo', 'Rojo', 'Gris', 'Morado'],
        characteristics: 'Eficiencia filtración 95%, 5 capas incluyendo meltblown, resistencia respiración <120Pa, ajuste nasal metálico, bandas elásticas, certificación GB2626-2006',
        wholesale: true,
        discount: false
    },
    40: {
        id: 40,
        title: 'Mascarilla N95',
        price: 3800,
        description: 'Mascarilla cónica, con tira de nariz ajustable para evitar la entrada de aire contaminado, polvo, bacterias y virus.',
        rating: 5,
        reviews: 298,
        review: "La forma cónica permite respirar con más comodidad. Sella muy bien alrededor de la nariz y boca. Ideal para procedimientos de alto riesgo.",
        images: ['../img/img1/producto41.png'],
        categories: 'Protección Personal, Mascarillas',
        tags: 'N95, Mascarilla, Protección',
        colors: ['Blanco'],
        characteristics: 'Diseño cónico 3D, eficiencia NIOSH 95%, espacio interno amplio, sello facial mejorado, válvula exhalación opcional, uso médico-industrial',
        wholesale: true,
        discount: false
    },
    41: {
        id: 41,
        title: 'Mascarilla KF94',
        price: 3800,
        description: 'Esta mascarilla protectora cuenta con cuatro capas y con un clip nasal metálico para poder ajustarlo mejor, desechables. Paquete con 10 o 20 unidades.',
        rating: 4,
        reviews: 234,
        review: "Me encantan estas mascarillas coreanas. El diseño es más estético y quedan bien ajustadas sin apretar. Muy cómodas para usar varias horas.",
        images: ['../img/img2/producto42.png'],
        categories: 'Protección Personal, Mascarillas',
        tags: 'KF94, Mascarilla, Coreana',
        colors: ['Blanco', 'Rosa', 'Negro', 'Verde', 'Azul', 'Naranja', 'Amarillo', 'Rojo', 'Gris', 'Morado'],
        characteristics: 'Estándar coreano KF94, 4 capas protección, eficiencia 94%, diseño plegable 3D, clip nasal ajustable, resistencia respiración 70Pa',
        wholesale: true,
        discount: false
    },
    42: {
        id: 42,
        title: 'Cubre Boca',
        price: 2000,
        description: 'Tira de nariz ajustable, evita la entrada de aire contaminado, 3 capas, desechables, varios colores y estampados disponibles. Caja con 50 unidades.',
        rating: 4,
        reviews: 189,
        review: "Para uso general son perfectas. Los estampados son lindos y agradan a los pacientes pediátricos. Buena relación calidad-precio para uso diario.",
        images: ['../img/img2/producto43.png'],
        categories: 'Protección Personal, Mascarillas',
        tags: 'Cubre Boca, Desechable, Protección',
        colors: ['Blanco', 'Rosa', 'Negro', 'Verde', 'Morado', 'Celeste'],
        characteristics: '3 capas no tejido, eficiencia bacteriana 98%, diseño plano plisado, elásticos oreja, gramaje 25gsm, colores y estampados variados',
        wholesale: true,
        discount: false
    },
    43: {
        id: 43,
        title: 'Vaselina en Pasta',
        price: 5500,
        description: 'En pasta para uso tópico, no irrita la piel, no produce mal olor, calma reacciones de la piel como picazón.',
        rating: 4,
        reviews: 156,
        review: "Perfecta para proteger y humectar la piel. La uso en procedimientos de estética y para proteger áreas sensibles. Textura suave y no grasosa.",
        images: ['../img/img2/producto44.png'],
        categories: 'Cuidado Personal, Dermatología',
        tags: 'Vaselina, Pasta, Piel',
        colors: ['Blanco'],
        characteristics: 'Petrolato USP 99.9%, consistencia pasta, oclusividad alta, protección barrera, uso tópico, envase 100g, pureza farmacéutica',
        wholesale: true,
        discount: false
    },
    44: {
        id: 44,
        title: 'Rollo Plástico',
        price: "Precio a cotizar",
        description: 'Rollo plástico fino, transparente, resistente y estirable, con diferentes usos, envuelve y protege las camillas de la suciedad y polvo. Tamaños: 18 pulgadas y 6 pulgadas.',
        rating: 4,
        reviews: 98,
        review: "Muy versátil para proteger equipos y camillas. Se adhiere bien y es resistente. El tamaño de 18 pulgadas es perfecto para camillas completas.",
        images: ['../img/img2/producto45.png'],
        categories: 'Protección, Insumos',
        tags: 'Rollo, Plástico, Protección',
        colors: ['Blanco'],
        characteristics: 'Polietileno 15 micras, ancho 45cm, largo 300m, transparente, auto adhesivo, protección camillas y equipos',
        wholesale: true,
        discount: false
    },
    45: {
        id: 45,
        title: 'Vasos de Cartón',
        price: 3300,
        description: 'Vasos desechables de cartón, amigable con el ambiente, utilizados en clínicas dentales y para el enjuague bucal de los pacientes capacidad de 3oz. Paquete: 50 unidades y 100 unidades.',
        rating: 4,
        reviews: 145,
        review: "Prefiero estos a los de plástico por ser más ecológicos. Son resistentes al agua y no se desarman. Mis pacientes aprecian el gesto ambiental.",
        images: ['../img/img2/producto46.png'],
        categories: 'Desechables, Odontología',
        tags: 'Vasos, Cartón, Desechables',
        colors: ['Blanco'],
        characteristics: 'Cartón kraft reciclable, capacidad 90ml, tratamiento parafina interior, base estable, diámetro boca 7cm, altura 8cm',
        wholesale: true,
        discount: false
    },
    46: {
        id: 46,
        title: 'Vasos Plásticos',
        price: 1500,
        description: 'Vasos desechables utilizados en clínicas dentales y para el enjuague bucal de los pacientes, es de plásticos, capacidad de 3 oz. Paquete con 50 unidades y 100 unidades.',
        rating: 4,
        reviews: 167,
        review: "Buenos vasos a precio accesible. La variedad de colores ayuda a organizar. Resistentes y del tamaño perfecto para enjuague bucal.",
        images: ['../img/img2/producto47.png'],
        categories: 'Desechables, Odontología',
        tags: 'Vasos, Plásticos, Desechables',
        colors: ['Blanco','Negro', 'Azul', 'Rosa', 'Morado', 'Celeste'],
        characteristics: 'Polipropileno transparente, capacidad 90ml, pared 0.3mm, estabilidad líquidos calientes, colores diferenciados, apilables',
        wholesale: true,
        discount: false
    },
    47: {
        id: 47,
        title: 'Rollo de Algodón',
        price: 3300,
        description: 'Algodón enrollado, se puede cortar según requiera el usuario, no estéril, es blanco, absorbente y purificado. Tamaño: 500 gramos.',
        rating: 4,
        reviews: 134,
        review: "Algodón de buena calidad. Muy absorbente y no suelta pelusa. Al venir en rollo puedo cortar el tamaño exacto que necesito. Rinde mucho.",
        images: ['../img/img2/producto48.png'],
        categories: 'Curación, Insumos Médicos',
        tags: 'Algodón, Rollo, Absorbente',
        colors: ['Blanco'],
        characteristics: 'Algodón hidrófilo 100%, peso 500g, ancho 5cm, largo 100m, absorción rápida, baja pelusidad, uso médico general',
        wholesale: true,
        discount: false
    },
    48: {
        id: 48,
        title: 'Algodón Torunda',
        price: 2800,
        description: 'La torunda es una bola de algodón, lista para usar, alta absorción. También es conocido como algodón en bolitas.',
        rating: 4,
        reviews: 189,
        review: "Súper prácticas las torundas ya hechas. Ahorran tiempo y todas son del mismo tamaño. Perfectas para limpieza y aplicación de antisépticos.",
        images: ['../img/img2/producto49.png'],
        categories: 'Curación, Insumos Médicos',
        tags: 'Algodón, Torunda, Bolitas',
        colors: ['Blanco'],
        characteristics: 'Bolas algodón prensado, diámetro 3cm, peso 0.5g unidad, alta densidad, absorción uniforme, empaque a granel 500 unidades',
        wholesale: true,
        discount: false
    },
    49: {
        id: 49,
        title: 'Rodillo Dental',
        price: 6800,
        description: 'Herramienta utilizada en odontología para diversas aplicaciones. Sirven para separar y aislar los tejidos, suave, flexible. Paquete con 500 y 1000 unidades.',
        rating: 4,
        reviews: 78,
        review: "Esenciales en mi práctica dental. Son suaves pero mantienen bien su forma. Ayudan mucho a mantener el campo seco y aislado durante procedimientos.",
        images: ['../img/img2/producto50.png'],
        categories: 'Odontología, Instrumental',
        tags: 'Rodillo, Dental, Odontología',
        colors: ['Blanco'],
        characteristics: 'Algodón grado odontológico, tamaño 3x4cm, compactación media, flexibilidad alta, esterilizable, uso aislamiento y secado',
        wholesale: true,
        discount: false
    },
    50: {
        id: 50,
        title: 'Guantes de Plástico',
        price: 1800,
        description: 'Son transparentes, ambidiestros, aptos para el contacto con alimentos. El uso de estos guantes permite evita la contaminación de productos que van a ser manipulados con las manos. Paquete con 100 unidades.',
        rating: 4,
        reviews: 156,
        review: "Perfectos para manipulación de alimentos en mi negocio. Son económicos y cumplen su función. Fáciles de poner y transparentes.",
        images: ['../img/img2/producto51.png'],
        categories: 'Protección, Guantes',
        tags: 'Guantes, Plástico, Alimentos',
        colors: ['Blanco'],
        characteristics: 'Polietileno 15 micras, transparente, ambidiestro, talla única, aprobación contacto alimentos, peso 2g por guante',
        wholesale: false,
        discount: false
    },
    51: {
        id: 51,
        title: 'Latex Bajos en Polvo',
        price: 2000,
        description: 'Gran adaptabilidad a la mano, mayor sensibilidad al tacto, ambidiestro, hecho de caucho natural, biodegradable gran protección ante químicos y fluidos corporales, puede causar reacciones alérgicas. Caja con 100 unidades.',
        rating: 4,
        reviews: 234,
        review: "Excelente sensibilidad táctil para procedimientos delicados. Se ajustan muy bien a la mano. El bajo polvo es importante para evitar irritación.",
        images: ['../img/img2/producto52.png'],
        categories: 'Protección, Guantes',
        tags: 'Latex, Bajos Polvo, Guantes',
        colors: ['Blanco', 'Rosa', 'Negro', 'Naranja', 'Morado', 'Celeste'],
        characteristics: 'Latex natural, polvo maíz <2mg, espesor 0.08mm, sensibilidad alta, biodegradabilidad 90%, colores diferenciados por talla',
        wholesale: true,
        discount: false
    },
    52: {
        id: 52,
        title: 'Latex Sin Polvo',
        price: 2500,
        description: 'Gran adaptabilidad a la mano, mayor sensibilidad al tacto, ambidiestro, hecho de caucho natural, biodegradable gran protección ante químicos y fluidos corporales, puede causar reacciones alérgicas. Caja con 100 unidades.',
        rating: 5,
        reviews: 189,
        review: "Los mejores guantes de látex que he usado. Sin polvo es fundamental para no contaminar heridas. Excelente elasticidad y resistencia.",
        images: ['../img/img2/producto53.png'],
        categories: 'Protección, Guantes',
        tags: 'Latex, Sin Polvo, Guantes',
        colors: ['Blanco'],
        characteristics: 'Latex 100% natural, libre de polvo, tratamiento cloración, espesor 0.1mm, elasticidad 800%, sensibilidad extrema',
        wholesale: true,
        discount: false
    },
    53: {
        id: 53,
        title: 'Vinyl',
        price: 2500,
        description: 'Ambidiestro, libre de polvo, mayor permeabilidad, libre de látex y es usualmente usado en el manejo de alimentos y para tareas de corta duración, menor adaptación. Caja con 100 unidades.',
        rating: 4,
        reviews: 167,
        review: "Ideales para personas con alergia al látex. Buenos para tareas rápidas y manipulación de alimentos. Precio muy competitivo.",
        images: ['../img/img2/producto54.png'],
        categories: 'Protección, Guantes',
        tags: 'Vinyl, Guantes, Alimentos',
        colors: ['Blanco'],
        characteristics: 'PVC plastificado, libre latex y polvo, ambidiestro, permeabilidad media, uso alimentario, espesor 0.08mm',
        wholesale: true,
        discount: false
    },
    54: {
        id: 54,
        title: 'Guantes de Alto Riesgo',
        price: 3500,
        description: 'Diseñado para protección personal y proporcionar seguridad adicional en entornos de trabajo con riesgos elevados para la salud de los trabajadores. Son utilizados en procedimientos con riesgo de contacto con agentes químicos, físicos y biológicos, y protegen contra cortes, punciones y contacto con sustancias peligrosas, son más largos y gruesos.',
        rating: 5,
        reviews: 89,
        review: "La protección extra que necesito para procedimientos de alto riesgo. Son más gruesos pero no pierdes mucha sensibilidad. Me dan tranquilidad.",
        images: ['../img/img2/producto55.png'],
        categories: 'Protección, Guantes',
        tags: 'Alto Riesgo, Protección, Químicos',
        colors: ['Verde', 'Celeste'],
        characteristics: 'Nitrilo 100%, espesor 0.15mm, longitud 30cm, resistencia química nivel 3, protección mecánica, colores según riesgo',
        wholesale: true,
        discount: false
    },
    55: {
        id: 55,
        title: 'Guantes Texturizados',
        price: 4500,
        description: 'Agarre antideslizante, mayor resistencia y grosor, multiusos, sin polvo, no estéril, ambidiestro, gramaje: 8,5.',
        rating: 4,
        reviews: 134,
        review: "El texturizado es genial para mejor agarre de instrumentos. Son resistentes y duraderos. Los uso para procedimientos que requieren firmeza.",
        images: ['../img/img2/producto56.png'],
        categories: 'Protección, Guantes',
        tags: 'Texturizados, Antideslizante, Guantes',
        colors: ['Negro'],
        characteristics: 'Nitrilo texturizado, agarre micro-pattern, espesor 0.12mm, resistencia desgarro 18MPa, uso industrial-médico, color negro',
        wholesale: true,
        discount: false
    },
    56: {
        id: 56,
        title: 'Vinyl de Color',
        price: 3000,
        description: 'Ambidiestro, libre de polvo, mayor permeabilidad, libre de látex y es usualmente usado en el manejo de alimentos y para tareas de corta duración, menor adaptación, elaborado con 30% vinyl y 70% nitrilo, es mas resistente que el vinyl, pero menos resistente que el nitrilo. Caja con 100 unidades.',
        rating: 4,
        reviews: 156,
        review: "Me gusta la mezcla de vinyl y nitrilo, da mejor resistencia. Los colores son lindos y permiten coordinar con el uniforme o diferenciar tareas.",
        images: ['../img/img2/producto57.png'],
        categories: 'Protección, Guantes',
        tags: 'Vinyl, Color, Guantes',
        colors: ['Negro', 'Rosa', 'Morado','Celeste'],
        characteristics: 'Mezcla vinyl/nitrilo 30/70, colores vivos, libre latex, espesor 0.1mm, resistencia media, diferenciación visual tareas',
        wholesale: true,
        discount: false
    },
    57: {
        id: 57,
        title: 'Guantes de Nitrilo',
        price: 2500,
        description: 'Hecho de caucho sintético, se adapta bien a la mano, no produce alergia, texturizado en la punta de los dedos, ambidiestro, libre de polvo, y libre de látex, gran variedad de colores. Caja con 100 unidades.',
        rating: 5,
        reviews: 278,
        review: "Mis guantes favoritos! No causan alergia, son resistentes y cómodos. El texturizado en los dedos da excelente agarre. Gran variedad de colores.",
        images: ['../img/img2/producto58.png'],
        categories: 'Protección, Guantes',
        tags: 'Nitrilo, Guantes, Sin Látex',
        colors: ['Negro', 'Rosa', 'Celeste', 'Morado', 'Blanco'],
        characteristics: 'Nitrilo 100% sintético, texturizado punta dedos, espesor 0.08mm, resistencia química, colores diferenciados, libre alergenos',
        wholesale: true,
        discount: false
    },
    58: {
        id: 58,
        title: 'Guantes Afelpados',
        price: 1500,
        description: 'Guantes multipropósito cuidan tus manos y uñas; son tan delgados que permitirán que no pierdas sensibilidad al lavar. Su superficie texturizada sobre la palma de la mano ayuda a evitar que se te resbalen los platos vasos y utensilios.',
        rating: 4,
        reviews: 189,
        review: "Perfectos para limpieza en la clínica. Protegen las manos sin perder sensibilidad. El afelpado interior es suave y no irrita la piel.",
        images: ['../img/img2/producto59.png'],
        categories: 'Limpieza, Protección',
        tags: 'Afelpados, Lavado, Protección',
        colors: ['Blanco'],
        characteristics: 'Poliéster afelpado interior, textura antideslizante palma, espesor 0.5mm, lavable reusable, talla única, protección térmica básica',
        wholesale: true,
        discount: false
    },
    59: {
        id: 59,
        title: 'Guantes Quirúrgicos',
        price: 14000,
        description: 'Guantes de látex estériles, mayor elasticidad, resistencia al desgarro, superficie micro texturizada un excelente agarre del instrumento y acabado antideslizante. Caja con 50 pares.',
        rating: 5,
        reviews: 145,
        review: "Calidad quirúrgica real. La microtextura da un agarre perfecto de instrumentos. Muy elásticos y resistentes. Indispensables para cirugías.",
        images: ['../img/img2/producto60.png'],
        categories: 'Quirúrgico, Guantes',
        tags: 'Quirúrgicos, Estériles, Látex',
        colors: ['Blanco'],
        characteristics: 'Latex estéril quirúrgico, microtextura completa, espesor 0.18mm, esterilidad garantizada, prueba aire, cumple ASTM D3577',
        wholesale: true,
        discount: false
    },
    60: {
        id: 60,
        title: 'Papel para Camilla',
        price: 3000,
        description: 'Para proteger las camillas y para ofrecer una mayor higiene durante la atención de los clientes. Tamaño: 54cm x 38mts.',
        rating: 4,
        reviews: 112,
        review: "Rollo de buen tamaño que rinde mucho. El papel es resistente y no se rompe fácilmente. Esencial para mantener la higiene en cada consulta.",
        images: ['../img/img2/producto61.png'],
        categories: 'Estética, Insumos',
        tags: 'Papel, Camilla, Protección',
        colors: ['Blanco'],
        characteristics: 'Papel kraft médico, ancho 54cm, largo 38m, resistencia humedad, no tejido, dispensador compatible, cambio rápido entre pacientes',
        wholesale: true,
        discount: false
    },
    61: {
        id: 61,
        title: 'Paletas de Madera',
        price: 1000,
        description: 'Se puedes mezclar, batir y aplicar productos como cremas, ceras y gel conductor, no estéril. Producto descartable hecho de madera 100% natural de superficie suave. Paquete con 100 unidades.',
        rating: 4,
        reviews: 134,
        review: "Muy versátiles en mi spa. Las uso para mezclar mascarillas, aplicar cera y otros productos. La madera natural no reacciona con los productos.",
        images: ['../img/img2/producto62.png'],
        categories: 'Estética, Desechables',
        tags: 'Paletas, Madera, Aplicadores',
        colors: ['Blanco'],
        characteristics: 'Madera abedul natural, tamaño 15cm, punta plana/ancha, superficie lisa, no reactiva, biodegradable, uso cosmético',
        wholesale: true,
        discount: false
    },
    62: {
        id: 62,
        title: 'Oxímetro',
        price: 16000,
        description: 'Ayuda a medir la cantidad de oxígeno que posee nuestra sangre, se adapta a los diferentes tamaños de dedos.',
        rating: 5,
        reviews: 267,
        review: "Instrumento preciso y fácil de usar. Las lecturas son rápidas y confiables. Pantalla clara y se adapta bien a diferentes tamaños de dedos.",
        images: ['../img/img2/producto63.png'],
        categories: 'Monitoreo, Médico',
        tags: 'Oxímetro, Saturación, Salud',
        colors: ['Blanco'],
        characteristics: 'Pantalla OLED, rango SpO2 70-99%, precisión ±2%, medición pulso 30-250bpm, batería Li-ion, tamaño dedos 8-25mm',
        wholesale: false,
        discount: false
    },
    63: {
        id: 63,
        title: 'K9 Pro',
        price: 40000,
        description: 'Control automatizado de medición de temperatura corporal con aerosol integrado que hace que la desinfección de las manos sea más conveniente y segura para todos los usuarios.',
        rating: 4,
        reviews: 78,
        review: "Inversión que vale la pena. Combina medición de temperatura y desinfección automática. Muy práctico en la entrada de mi clínica. Los pacientes lo aprecian.",
        images: ['../img/img2/producto64.png'],
        categories: 'Tecnología, Seguridad',
        tags: 'K9 Pro, Temperatura, Desinfección',
        colors: ['Blanco'],
        characteristics: 'Termómetro infrarrojo sin contacto, rango 34-42°C, precisión ±0.2°C, dispensador gel 70%, sensor distancia 5-15cm, pantalla LCD',
        wholesale: false,
        discount: false
    },
    64: {
        id: 64,
        title: 'Rollo de Papel Toalla',
        price: 4500,
        description: 'Rollo de toallas absorbentes y resistentes. Se recomienda para lugares que requieren de alta capacidad y valor. Es un producto de limpieza indispensable para proveer higiene en el secado de manos así como superficies.',
        rating: 4,
        reviews: 189,
        review: "Muy absorbente y resistente incluso mojado. El rollo grande rinde mucho en áreas de alto tráfico. Buena relación calidad-precio.",
        images: ['../img/img2/producto65.png'],
        categories: 'Limpieza, Higiene',
        tags: 'Papel, Toalla, Rollo',
        colors: ['Blanco'],
        characteristics: 'Papel 2 capas crepado, ancho 21cm, diámetro rollo 12cm, absorción 300ml/m², resistencia humedad, dispensador estándar',
        wholesale: false,
        discount: false
    },
    65: {
        id: 65,
        title: 'Toallas de Papel para Manos',
        price: 2000,
        description: 'Toallas interfolíadas, dispensadas una a una, evitando la contaminación cruzada, forma rectangular. Tamaño: 22,5cm x 23cm. Paquete con 200 unidades.',
        rating: 4,
        reviews: 156,
        review: "El sistema interfoliado es muy higiénico. Cada toalla sale limpia sin tocar las demás. Buen tamaño y absorción para secado de manos.",
        images: ['../img/img2/producto66.png'],
        categories: 'Limpieza, Higiene',
        tags: 'Toallas, Papel, Manos',
        colors: ['Blanco'],
        characteristics: 'Sistema interfoliado, tamaño 22.5x23cm, 2 capas, absorción rápida, dispensación individual, paquete 200 unidades',
        wholesale: true,
        discount: false
    },
    66: {
        id: 66,
        title: 'Bata Impermeable',
        price: 4500,
        description: 'Impermeable, plástica con sujeción, para usarse en procedimientos médicos con probabilidad de contacto con fluidos corporales o portadores de patógenos, espalda abierta. No estéril. Paquete con 10 unidades.',
        rating: 5,
        reviews: 134,
        review: "Protección excelente contra salpicaduras. El material impermeable cumple su función perfectamente. Cómodas y fáciles de poner y quitar.",
        images: ['../img/img2/producto67.png'],
        categories: 'Protección, Ropa Médica',
        tags: 'Bata, Impermeable, Protección',
        colors: ['Celeste'],
        characteristics: 'Polietileno 35 micras, diseño espalda abierta, sello neck-guard, mangas largas, protección nivel 4, talla única',
        wholesale: true,
        discount: false
    },
    67: {
        id: 67,
        title: 'Camilla Hidráulica',
        price: "Precio a cotizar",
        description: 'Brazos abatibles y ajustable soporte de piernas ajustables, cabecera removible, pistón de aire para ajustar la altura.',
        rating: 5,
        reviews: 45,
        review: "Excelente inversión para mi clínica. El sistema hidráulico funciona suave y silenciosamente. Los ajustes son fáciles y la comodidad para el paciente es notable.",
        images: ['../img/img2/producto68.png'],
        categories: 'Equipamiento, Médico',
        tags: 'Camilla, Hidráulica, Ajustable',
        colors: ['Blanco'],
        characteristics: 'Sistema hidráulico bomba pedal, altura 65-95cm, estructura acero, tapizado vinílico, peso máximo 180kg, ruedas bloqueables',
        wholesale: false,
        discount: false
    },
    68: {
        id: 68,
        title: 'Banco Giratorio con Respaldo',
        price: "Precio a cotizar",
        description: 'Hecho de aluminio, hierro esmaltado y vinyl, altura ajustable, con respaldar, varios colores a elegir.',
        rating: 4,
        reviews: 67,
        review: "Muy cómodo para trabajar largas horas. El respaldo da buen soporte lumbar. El mecanismo de altura funciona perfecto. Material de calidad.",
        images: ['../img/img2/producto69.png'],
        categories: 'Muebles, Estética',
        tags: 'Banco, Giratorio, Respaldo',
        colors: ['Blanco'],
        characteristics: 'Estructura aluminio, asiento vinílico, altura 50-70cm, giro 360°, respaldo lumbar, capacidad 120kg, base 5 patas',
        wholesale: false,
        discount: false
    },
    69: {
        id: 69,
        title: 'Canilla Fija',
        price: "Precio a cotizar",
        description: 'Camillas cómoda, resistente, fija, soporta un peso aproximado de 150 kilos, apta para realizar masajes, tatuajes, microblading, lashista, etc. 6 diferentes estilos y varios colores a elegir.',
        rating: 4,
        reviews: 89,
        review: "Camilla sólida y estable. Perfecta para mi sala de masajes. El acolchado es cómodo y la estructura no hace ruidos. Buena capacidad de peso.",
        images: ['../img/img2/producto70.png'],
        categories: 'Muebles, Estética',
        tags: 'Canilla, Fija, Masajes',
        colors: ['Blanco'],
        characteristics: 'Estructura acero 2mm, tapizado cuero ecológico, espesor espuma 10cm, altura 75cm, peso máximo 150kg, acabado epoxy',
        wholesale: false,
        discount: false
    },
    70: {
        id: 70,
        title: 'Banco Giratorio sin Respaldo',
        price: "Precio a cotizar",
        description: 'Hecho de aluminio, hierro esmaltado y vinyl, altura ajustable, sin respaldar, varios colores a elegir.',
        rating: 4,
        reviews: 56,
        review: "Banco práctico y ligero. La falta de respaldo permite mayor movilidad. Perfecto para procedimientos donde necesito moverme constantemente.",
        images: ['../img/img2/producto71.png'],
        categories: 'Muebles, Estética',
        tags: 'Banco, Giratorio, Sin Respaldo',
        colors: ['Blanco'],
        characteristics: 'Aluminio anodizado, asiento vinílico, altura 45-65cm, giro libre, base estrella, peso 4.5kg, portátil',
        wholesale: false,
        discount: false
    },
    71: {
        id: 71,
        title: 'Camilla Tipo Maleta',
        price: 150000,
        description: 'Camillas cómoda, resistente, fácil de movilizar, soporta un peso aproximado de 150 kilos, apta para realizar masajes, tatuajes, microblading, lashista, etc. 6 diferentes estilos y varios colores a elegir.',
        rating: 5,
        reviews: 78,
        review: "Perfecta para servicio a domicilio. Se pliega fácil y es ligera para transportar. Una vez armada es muy estable y cómoda. Excelente compra.",
        images: ['../img/img2/producto72.png'],
        categories: 'Muebles, Portátil',
        tags: 'Camilla, Maleta, Portátil',
        colors: ['Blanco'],
        characteristics: 'Diseño plegable, peso 12kg, estructura aluminio, tapizado lavable, altura 65cm, peso máximo 120kg, asa transporte',
        wholesale: false,
        discount: false
    },
    72: {
        id: 72,
        title: 'Apoya Brazos',
        price: 45000,
        description: 'Hecho de aluminio, hierro esmaltado y vinyl, altura ajustable, varios colores a elegir.',
        rating: 4,
        reviews: 34,
        review: "Complemento perfecto para mi camilla. La altura ajustable permite adaptarlo a cada cliente. Muy útil para manicure y procedimientos en brazos.",
        images: ['../img/img2/producto73.png'],
        categories: 'Accesorios, Estética',
        tags: 'Apoya, Brazos, Ajustable',
        colors: ['Blanco'],
        characteristics: 'Ajuste altura 70-90cm, superficie vinílica, estructura aluminio, base estable, ancho 25cm, uso manicure y estética',
        wholesale: false,
        discount: false
    },
    73: {
        id: 73,
        title: 'Gorro de Cirugía',
        price: 4500,
        description: 'Diseñado paraproteger la cabeza y el cabello de los trabajadores de la salud de posibles contaminantes. Ofrece resistencia para proteger el cabello y el cuero cabelludo durante las cirugías. Paquete con 100 unidades.',
        rating: 4,
        reviews: 112,
        review: "Gorros de buena calidad para uso quirúrgico. Cubren bien todo el cabello y tienen buen ajuste. El material no irrita la piel durante uso prolongado.",
        images: ['../img/img2/producto74.png'],
        categories: 'Protección Personal, EPP',
        tags: 'Gorro, Cirugía, Protección',
        colors: ['Blanco'],
        characteristics: 'Polipropileno no tejido, diseño bouffant, elástico suave, cobertura completa, peso 8g, esterilización gamma',
        wholesale: true,
        discount: false
    },
    74: {
        id: 74,
        title: 'Careta Protectora',
        price: 500,
        description: 'Barrera simple para ayudar a evitar que las gotas respiratorias viajen en el aire y sobre otras personas, ligero y cómodo.',
        rating: 4,
        reviews: 189,
        review: "Muy ligera y práctica. No se empaña tanto como otras caretas. La banda elástica ajusta bien y no aprieta. Buena protección a bajo costo.",
        images: ['../img/img2/producto75.png'],
        categories: 'Protección Personal, EPP',
        tags: 'Careta, Protectora, Facial',
        colors: ['Blanco'],
        characteristics: 'Policarbonato 0.5mm, banda elástica ajustable, visibilidad 180°, peso 45g, protección salpicaduras, limpieza fácil',
        wholesale: false,
        discount: false
    },
    75: {
        id: 75,
        title: 'Careta con Lentes',
        price: 500,
        description: 'Barrera simple para ayudar a evitar que las gotas respiratorias viajen en el aire y sobre otras personas, ligero y cómodo, hecha de material PET. Espacio para anteojos o gafas. Caja con 6 unidades.',
        rating: 5,
        reviews: 145,
        review: "Por fin una careta que puedo usar con mis anteojos! El espacio extra es perfecto. Material resistente y visibilidad clara. Muy cómoda.",
        images: ['../img/img2/producto76.png'],
        categories: 'Protección Personal, EPP',
        tags: 'Careta, Lentes, Protección',
        colors: ['Blanco'],
        characteristics: 'PET 0.3mm, diseño espacio anteojos, elástico suave, protección facial completa, pack 6 unidades, almacenamiento plano',
        wholesale: false,
        discount: false
    },
    76: {
        id: 76,
        title: 'Kimono Protector',
        price: 4800,
        description: 'Traje de protección, hecho de un material resistente el cual ayuda a proporcionar una barrera de protección contra salpicaduras de líquidos, polvos tóxicos y ciertos contaminantes biológicos.',
        rating: 4,
        reviews: 89,
        review: "Protección completa para procedimientos de alto riesgo. El material es resistente pero respirable. Cubre muy bien sin restringir movimiento.",
        images: ['../img/img2/producto77.png'],
        categories: 'Protección, Ropa Médica',
        tags: 'Kimono, Protector, Barrera',
        colors: ['Blanco'],
        characteristics: 'Tyvek 45gsm, costuras selladas, cierre frontal completo, capucha integrada, tallas S-XXL, protección partículas 0.5 micras',
        wholesale: false,
        discount: false
    },
    77: {
        id: 77,
        title: 'Dispensador de Agua',
        price: 5000,
        description: 'Dispensador de agua electrónico, botón touch para dispensar agua con doble motor para mas velocidad, ideal para tu garrafón de agua, muy practico, recargable, facil instalación.',
        rating: 4,
        reviews: 67,
        review: "Muy práctico para la sala de espera. El sistema touch es higiénico. Dispensa rápido y no gotea. La batería recargable dura bastante.",
        images: ['../img/img2/producto78.png'],
        categories: 'Equipamiento, Oficina',
        tags: 'Dispensador, Agua, Electrónico',
        colors: ['Blanco'],
        characteristics: 'Sistema touch electrónico, doble motor 12V, batería 2000mAh, capacidad garrafón 20L, flujo 1.5L/min, material ABS alimentario',
        wholesale: false,
        discount: false
    },
    78: {
        id: 78,
        title: 'Dispensador de Toalla',
        price: "Precio a cotizar",
        description: 'Diseñado para la dispensación controlada de toallas de papel, usado principalmente en baños, cocinas o áreas de trabajo donde se requiere higiene.',
        rating: 4,
        reviews: 78,
        review: "Dispensador robusto y funcional. Controla bien el uso de toallas. Fácil de rellenar y el sistema de palanca funciona suave.",
        images: ['../img/img2/producto79.png'],
        categories: 'Equipamiento, Higiene',
        tags: 'Dispensador, Toalla, Papel',
        colors: ['Blanco'],
        characteristics: 'Acero inoxidable 304, mecanismo palanca, capacidad 200 toallas, montaje pared, protección anti-vandalismo, fácil recarga',
        wholesale: false,
        discount: false
    },
    79: {
        id: 79,
        title: 'Dispensador en Rollo',
        price: "Precio a cotizar",
        description: 'Diseñado para suministrar toalla de papel en rollo, ideal para el secado de manos en baños, cocinas o áreas industriales.',
        rating: 4,
        reviews: 56,
        review: "Perfecto para áreas de alto tráfico. El mecanismo de corte automático funciona bien. Acepta rollos grandes lo que reduce el mantenimiento.",
        images: ['../img/img2/producto80.png'],
        categories: 'Equipamiento, Higiene',
        tags: 'Dispensador, Rollo, Toalla',
        colors: ['Blanco'],
        characteristics: 'Diseño para rollo jumbo, corte automático, acero inoxidable, ancho rollo 21cm, diámetro máximo 15cm, montaje superficie',
        wholesale: false,
        discount: false
    },
    80: {
        id: 80,
        title: 'Gafa de Seguridad',
        price: "Precio a cotizar",
        description: 'Para la protección ocular en diversas actividades laborales, industriales, médicas o de laboratorio. Protección contra salpicaduras químicas, polvo o partículas.',
        rating: 4,
        reviews: 134,
        review: "Protección confiable para los ojos. Se ajustan bien sobre anteojos regulares. No se empañan fácilmente y son cómodas para uso prolongado.",
        images: ['../img/img2/producto81.png'],
        categories: 'Protección Personal, EPP',
        tags: 'Gafa, Seguridad, Ocular',
        colors: ['Blanco'],
        characteristics: 'Lente policarbonato, protección UV400, montura flexible, ventilación indirecta, ajuste universal, cumple ANSI Z87.1',
        wholesale: false,
        discount: false
    },
    81: {
        id: 81,
        title: 'Lentes de Seguridad',
        price: "Precio a cotizar",
        description: 'Patillas ajustables. Se usan para proteger los ojos de distintos peligros en el entorno. Protección contra impacto evitando partículas, astillas de madera, metal o fragmentos de vidrio golpeen los ojos, protección contra salpicaduras químicas y protección contra polvo y escombros.',
        rating: 5,
        reviews: 189,
        review: "Lentes ligeros y cómodos. Las patillas ajustables permiten un fit perfecto. Protección adecuada sin sacrificar visibilidad periférica.",
        images: ['../img/img2/producto82.png'],
        categories: 'Protección Personal, EPP',
        tags: 'Lentes, Seguridad, Protección',
        colors: ['Blanco'],
        characteristics: 'Diseño tipo gafas, patillas ajustables, lente anti-rayas, protección lateral, peso 25g, protección impacto alta velocidad',
        wholesale: false,
        discount: false
    },
    82: {
        id: 82,
        title: 'Basurero Rojo',
        price: "Precio a cotizar",
        description: 'Un basurero para residuos bioinfecciosos está diseñado para desechar materiales que puedan transmitir enfermedades (como gasas con sangre, agujas, guantes contaminados, etc.). Obligatorio en hospitales, clínicas, laboratorios y lugares donde se generen desechos biológicos.',
        rating: 4,
        reviews: 67,
        review: "Esencial para cumplir con normas de bioseguridad. El color rojo es claramente identificable. Pedal para apertura sin contacto, muy higiénico.",
        images: ['../img/img2/producto83.png'],
        categories: 'Equipamiento, Hospitalario',
        tags: 'Basurero, Rojo, Bioinfeccioso',
        colors: ['Blanco'],
        characteristics: 'Color rojo riesgo biológico, capacidad 30L, pedal apertura, material polipropileno, tapa con sello, bolsa compatible 40x50cm',
        wholesale: false,
        discount: false
    },
    83: {
        id: 83,
        title: 'Recipiente Rojo',
        price: 1250,
        description: 'Para almacenamiento específico de elementos de uso quirúrgico o de curación como gasas, baja lenguas, algodón, aplicadores, agujas, jeringas, guantes.',
        rating: 4,
        reviews: 45,
        review: "Recipiente resistente para desechos punzocortantes. La tapa de seguridad evita accidentes. Buen tamaño para uso en consultorios.",
        images: ['../img/img2/producto84.png'],
        categories: 'Equipamiento, Hospitalario',
        tags: 'Recipiente, Rojo, Quirúrgico',
        colors: ['Blanco'],
        characteristics: 'Policarbonato resistente, capacidad 1L, tapa seguridad, color rojo punzocortantes, autoclavable, graduación volumétrica',
        wholesale: false,
        discount: false
    },
    84: {
        id: 84,
        title: 'Jeringas Desechables',
        price: "Precio a cotizar",
        description: 'Diseñadas para ofrecer la máxima precisión y comodidad en cada uso. Asegura una punción suave y reducir al mínimo el dolor en el paciente. Estéril y desechable.',
        rating: 5,
        reviews: 278,
        review: "Jeringas de excelente calidad. El émbolo se desliza suave. Las agujas son muy afiladas lo que minimiza el dolor. Graduaciones claras y precisas.",
        images: ['../img/img2/producto85.png'],
        categories: 'Insumos Médicos, Desechables',
        tags: 'Jeringas, Desechables, Estériles',
        colors: ['Blanco'],
        characteristics: 'Estéril por radiación gamma, capacidad 3ml, aguja 25G, escala 0.1ml, émbolo siliconizado, triple esterilización',
        wholesale: false,
        discount: false
    },
    85: {
        id: 85,
        title: 'Gasa Estéril',
        price: 6800,
        description: 'Diseñada para usarse directamente sobre heridas abiertas o durante procedimientos médicos y quirúrgicos; Permite limpiar, cubrir y proteger heridas, absorber fluidos y aplicar medicamentos sin riesgo de contaminación.',
        rating: 5,
        reviews: 189,
        review: "La esterilidad es perfecta para uso quirúrgico. Muy absorbentes y no dejan residuos en las heridas. Empaque individual muy práctico.",
        images: ['../img/img2/producto86.png'],
        categories: 'Curación, Insumos Médicos',
        tags: 'Gasa, Estéril, Quirúrgica',
        colors: ['Blanco'],
        characteristics: 'Estéril por óxido etileno, tamaño 10x10cm 8 capas, absorción 12g/g, baja pelusidad, empaque individual, esterilidad 2 años',
        wholesale: false,
        discount: false
    },
    86: {
        id: 86,
        title: 'Gasa Tejida',
        price: 5500,
        description: 'Tejido entrelazado que permite el paso de aire y la absorción de líquidos; se utiliza en la limpieza y protección de heridas, aplicación de medicamentos y absorción de fluidos.',
        rating: 4,
        reviews: 156,
        review: "Gasa de buena densidad. El tejido permite que las heridas respiren. No se adhiere a las lesiones. Buena relación calidad-precio.",
        images: ['../img/img2/producto87.png'],
        categories: 'Curación, Insumos Médicos',
        tags: 'Gasa, Tejida, Absorbente',
        colors: ['Blanco'],
        characteristics: 'Tejido plano 44 hilos, 100% algodón, tamaño 10x10cm, esterilización gamma, porosidad controlada, empaque 100 unidades',
        wholesale: false,
        discount: false
    },
    87: {
        id: 87,
        title: 'Mascarilla de Niños',
        price: 1800,
        description: 'Diseñadas para reducir la propagación de partículas de la persona que las usa. Existen diferentes modelos y diseños.',
        rating: 4,
        reviews: 167,
        review: "Perfectas para los pequeños pacientes. El tamaño es adecuado para caras infantiles. Los diseños coloridos hacen que los niños las usen sin problema.",
        images: ['../img/img2/producto88.png'],
        categories: 'Protección Personal, Mascarillas',
        tags: 'Mascarilla, Niños, Protección',
        colors: ['Blanco'],
        characteristics: 'Tamaño infantil 12x7cm, 3 capas no tejido, elásticos suaves oreja, diseños infantiles, eficiencia bacteriana 95%, peso 3g',
        wholesale: false,
        discount: false
    }
};
